### ISSUE TITLE
About Remora and Megalodon

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/remora#10]
Hello, thank you very much for sharing this useful tool. I would like to know what is the difference between Remora and Megalodon? Aren't they tools to call base modification?

**Comment by marcus1487** [comment]
Megalodon performs many other tasks outside of the "modified base calling" task. As found in the megalodon project description these tasks are generally referred to as "basecalling augmentation". Remora provides a smaller interface for training Remora modified base models and a very simple interface for applying these models (`remora infer`). Specifically Remora does not provide the interface for efficiently running the basecaller and processing these results to produce modbase outputs in the variety of formats available from megalodon.

Remora is not intended to be run as a standalone program (aside from model training) for end users. Remora is instead used as the backend for both Megalodon and Bonito to provide the highest accuracy modified base calls alongside the canonical basecalls. The same algorithms are being added to Guppy in a more highly optimized implementation for highly accurate production release of modified base calling.
