### ISSUE TITLE
AttributeError in Read.add_alignment method of remora/io.py

### ISSUE THREAD

**Issue by harikaurel** [nanoporetech/remora#101]
Hi,

While trying to use the `remora` library within metrics_api.ipynb, I encountered an `AttributeError` when calling the `Read.add_alignment` method.

   ```python
   bam_read = next(can_bam_fh)
   pod5_read = next(can_pod5_fh.reads(selection=[bam_read.query_name]))
   io_read = io.Read.from_pod5_and_alignment(pod5_read, bam_read)
   ```
The error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 6
      4 print(bam_read.query_name)
      5 print(pod5_read.signal)
----> 6 io_read = io.Read.from_pod5_and_alignment(pod5_read, bam_read)
      7 # io_read.ref_reg

File [~/sc_venv_template/venv/lib/python3.10/site-packages/remora/io.py:1570](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22686169636c7573746572312e667a2d6a75656c6963682e6465222c2275736572223a227572656c31227d.vscode-resource.vscode-cdn.net/home/urel1/harika/remora/notebooks/~/sc_venv_template/venv/lib/python3.10/site-packages/remora/io.py:1570), in Read.from_pod5_and_alignment(cls, pod5_read_record, alignment_record, reverse_signal)
   1563     dacs = dacs[::-1]
   1564 read = Read(
   1565     read_id=str(pod5_read_record.read_id),
   1566     dacs=dacs,
   1567     shift_dacs_to_pa=pod5_read_record.calibration.offset,
   1568     scale_dacs_to_pa=pod5_read_record.calibration.scale,
   1569 )
-> 1570 read.add_alignment(alignment_record, reverse_signal=reverse_signal)
   1571 return read

File [~/sc_venv_template/venv/lib/python3.10/site-packages/remora/io.py:1540](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22686169636c7573746572312e667a2d6a75656c6963682e6465222c2275736572223a227572656c31227d.vscode-resource.vscode-cdn.net/home/urel1/harika/remora/notebooks/~/sc_venv_template/venv/lib/python3.10/site-packages/remora/io.py:1540), in Read.add_alignment(self, alignment_record, parse_ref_align, reverse_signal)
   1538     self.cigar = self.cigar[::-1]
   1539 if self.ref_reg.ctg is not None and self.ref_seq is not None:
-> 1540     self.ref_to_signal = DC.compute_ref_to_signal(
   1541         query_to_signal=self.query_to_signal,
   1542         cigar=self.cigar,
...
    112     return map_ref_to_signal(
    113         query_to_signal=query_to_signal, ref_to_query_knots=ref_to_read_knots
    114     )

AttributeError: 'NoneType' object has no attribute 'size'

I would like to print an output detailing which data points match specific bases for the provided raw signal. Is there an existing function in the library for this?

**Comment by marcus1487** [comment]
We will improve this error message in the next release, but it looks like you might not have a move table in your BAM file. Can you add these (`--emit-moves` option in Dorado) and try to run your code again.
