### ISSUE TITLE
How to obtain the methylation track in IGV

### ISSUE THREAD

**Issue by carolinehey** [nanoporetech/remora#107]
Hello,

I would like to include the top haplotype specific methylation prop. track found in the screenshot below from epi2me (https://labs.epi2me.io/gm24385-5mc-remora/)

![image](https://github.com/nanoporetech/remora/assets/98043249/520477a5-05c0-4747-8916-e6d121d1d505)

How can this be done?

**Comment by ArtRand** [comment]
Hello @carolinehey 
I believe that is a bedMethyl track that can be generated with our [modkit tool](https://github.com/nanoporetech/modkit/). The [documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html) has some examples of how to generate these tracks.
