### ISSUE TITLE
Training remora for use with bonito

### ISSUE THREAD

**Issue by snajder-r** [nanoporetech/remora#11]
Hi!

I'm excited to try to train remora for additional base modifications.

The Remora Readme describes how to create training data using megalodon and taiyaki and then states 

"This command will produce a final model in ONNX format for use in Bonito, Megalodon or remora infer commands."

I just wanted to be extra sure and ask: If I use megalodon and taiyaki as described above, will a Remora model trained that way be usable with Bonito? Or would I need to then also perform inference using megalodon+remora? Are there separate instructions how to generate a training dataset for remora using bonito?

**Comment by marcus1487** [comment]
Yes a Remora model trained from data prepared by Megalodon/Taiyaki is usable with Bonito. We are working to unify versions of basecalling models between Bonito and Guppy. Different basecalling models may have slight impacts on performance of the associated Remora model. The inference using Megalodon/Remora would be the best way at this time to confirm that the same canonical basecalling model was used at data prep and inference time right now.

There are no instructions at this time to construct a Remora training dataset from Bonito. Bonito is not a feature rich as Megalodon at this time.
