### ISSUE TITLE
Remora infer on bed specified regions

### ISSUE THREAD

**Issue by andrewgalbraith21** [nanoporetech/remora#115]
Hello I am wondering if there has been any thoughts on adding a similar parameter as --focus-reference-position in remora dataset prepare to remora infer. I have been wanting to test on only a set of bed specified regions and have not found any inherent functionality to do this. So far, I've been calling mods for reads in the regions of interest and then using bedtools intersect to only extract wanted calls. While this works, its a fairly inefficient work around and I think it would be nice to be able to specify a bed file in remora infer. Let me know if this is in consideration or if you have a better proposed workaround for this. Thank so much!

**Comment by marcus1487** [comment]
I think this might complicate the Remora code a bit too much for my liking. The Remora inference code calls all valid bases. Adding options to filter which calls are made would add quite a bit of complexity to the core code and make it more bug prone as well as making the options a bit confusing (e.g. how would this option interact with basecall-anchored modified base calls). I think your workaround to extract the overlapping reads from the BAM file and extract the calls from processed BAM is the correct workaround. Note that modkit takes a bed as input for pileup as well as other common commands, so your bedtools intersect may not be necessary simplifying your pipeline a bit.

**Comment by andrewgalbraith21** [comment]
Hello @marcus1487 your reasoning makes sense, thanks so much for the quick reply.
