### ISSUE TITLE
ref to signal mapping did not consider splicing

### ISSUE THREAD

**Issue by chilampoon** [nanoporetech/remora#118]
Hi @marcus1487, I was using remora API on real direct RNA-seq data, but ran into errors from this command:

```python
  io_read = Read.from_pod5_and_alignment(
      pod5_read_record=pod5_reads[bam_read.query_name],
      alignment_record=bam_read,
      reverse_signal=True,
  )
  ```
  ```
  ---------------------------------------------------------------------------

File [/opt/miniconda3/lib/python3.11/site-packages/remora/io.py:1545](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/lib/python3.11/site-packages/remora/io.py:1545), in Read.add_alignment(self, alignment_record, parse_ref_align, reverse_signal)
   1540 self.ref_to_signal = DC.compute_ref_to_signal(
   1541     query_to_signal=self.query_to_signal,
   1542     cigar=self.cigar,
   1543 )
   1544 # +1 because knots include the end position of the last base
-> 1545 assert self.ref_to_signal.size == len(self.ref_seq) + 1, (
   1546     "discordant ref seq lengths: move+cigar:"
   1547     f"{self.ref_to_signal.size} ref_seq:{len(self.ref_seq)}"
   1548 )
   1549 self.ref_reg.end = self.ref_reg.start + self.ref_to_signal.size - 1

AssertionError: discordant ref seq lengths: move+cigar:16978 ref_seq:2542
```

Apparently `ref_seq:2542` is the number of bases of this gene's exonic regions (i.e. seq length of this read), and `move+cigar:16978` ~= ref_end - ref_start on the genomic region (i.e. the range of all exons and introns).

I then tried to resolve it, for [here](https://github.com/nanoporetech/remora/blob/8f4d61705f0304894b0da955439db52c48690a5a/src/remora/data_chunks.py#L101C1-L101C1) if changes to 

```
knots = np.interp(np.arange(query_knots[-1] + 1), query_knots, ref_knots)
```
will get the correct lengths as it uses reference knots and query knots to generate reference to read knots. Then for [map_ref_to_signal()](https://github.com/nanoporetech/remora/blob/8f4d61705f0304894b0da955439db52c48690a5a/src/remora/data_chunks.py#L54) I guess can just 

```
return np.floor(
        ref_to_query_knots
    ).astype(int)
```
then it gives `ref_to_signal` coordinate mapping. 
I haven't tested it further, but I can provide a toy dataset for this issue, thank you and looking forward to your comments.

**Comment by chilampoon** [comment]
> Remora is not currently designed to work with spliced RNA alignments. This is not currently on the roadmap, but is certainly possible. The fix would be to [this function primarily](https://github.com/nanoporetech/remora/blob/v2.1.3/src/remora/data_chunks.py#L71). I'd be happy to accept a PR for this, but need to ensure that it would not have any impact on standard genomic alignments.

Okay, I misunderstood something before but updated the understanding later on, I will open a PR soon. 

I wrote a function to get the query to reference mapping, and modified something to get the query to ref coordinates mappings -> this leads to a few differences from the original ref_to_signal values (for genomic reads) but they are more or less similar...  for example if I just `plt.plot(ref_to_signal)`. This read's cigar string is `3S10M1D24M1I5M1I7M1D34M1D16M2I15M1I7M1D6M1I12M1I1M2I11M2I5M3I20M15S `

<img width="553" alt="image" src="https://github.com/nanoporetech/remora/assets/43943114/6492cab4-daef-4035-94c6-f87bc03ca706">

<img width="557" alt="image" src="https://github.com/nanoporetech/remora/assets/43943114/0f157b90-84b6-4214-9068-fa1312b559cd">

it works for my spliced read mentioned above:
<img width="576" alt="image" src="https://github.com/nanoporetech/remora/assets/43943114/d7a36ea2-f485-4042-8dc2-8be0e8bb1b1d">


please review my PR, thank you very much!

**Comment by marcus1487** [comment]
I'm on paternity leave at the moment, so I won't be able to take a very close look at this for a little bit, but at a high level unless there is a clear reason I think any differences in produced genomic alignments will not be acceptable. If differences in genomic alignments are required to support the skip operation could you detail those here?

**Comment by chilampoon** [comment]
@marcus1487 I found out I don't need another interpolation in `map_ref_to_signal()` at all 🤦‍♀️ 

the spliced read's ref_to_signal is now like
<img width="400" alt="image" src="https://github.com/nanoporetech/remora/assets/43943114/6a008ae1-8b25-4971-8b2b-27dc34146d65">
where the last 73 bases are soft clippings.

I then tested the genomic/unspliced reads I have (I wrapped the steps into `get_manual_mappins()` - please ignore the type)

```python
matches = []
num_processed_reads = 0
for bam_read in bam_reads_reg:
    try:
        mapping = get_manual_mappins(bam_read, pod5_reads[bam_read.query_name])
        num_processed_reads += 1
    except:
        continue

    io_read = Read.from_pod5_and_alignment(
        pod5_read_record=pod5_reads[bam_read.query_name],
        alignment_record=bam_read,
        reverse_signal=True,
    )
    matches.append((mapping == io_read.ref_to_signal).all())
```

```
print(num_processed_reads)
np.unique(matches, return_counts=True)

66686
(array([ True]), array([66686]))
```
the results are all the same! sorry for the mess... all the stuff is a bit complicated. I'm still in awe that people like you can create such complex software, I am going to update the PR now

**Comment by marcus1487** [comment]
It seems that the core issue here has been resolved. Please re-open if you experience further issues.
