### ISSUE TITLE
Error while installing remora

### ISSUE THREAD

**Issue by keenhl** [nanoporetech/remora#123]
I get the following error when trying to install remora.

Could not find a version that satisfies the requirement pod5>=0.2 (from ont-remora) (from versions: )
No matching distribution found for pod5>=0.2 (from ont-remora)

Thanks for your help.

**Comment by keenhl** [comment]
Ok I tried on python 3.7, now I get the following error.

checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... no
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      configure: error: libbzip2 development files not found

**Comment by marcus1487** [comment]
This looks like an issue with pysam. Could you try to install pysam alone?

**Comment by marcus1487** [comment]
Sorry, you tried to install pysam and got this same error? Or you installed pysam successfully and then got this same error when installing remora?

**Comment by keenhl** [comment]
Sorry, my fault for the unclearness.  I successful installed pysam.  However, I am still getting the same error when I try to install remora as I did before installing pysam.

**Comment by marcus1487** [comment]
Could you provide the full output when you you run `pip install remora`? It is odd that pip tries to install pysam if it is already installed.

**Comment by keenhl** [comment]
Yes, thanks for looking into this.  Here is the full output.


pip install ont-remora
Collecting ont-remora
  Using cached ont-remora-2.1.3.tar.gz (95 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tqdm (from ont-remora)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting toml (from ont-remora)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting torch (from ont-remora)
  Using cached torch-1.13.1-cp37-cp37m-manylinux1_x86_64.whl (887.5 MB)
Collecting numpy (from ont-remora)
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting scikit-learn (from ont-remora)
  Using cached scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
Collecting tabulate (from ont-remora)
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting thop (from ont-remora)
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Collecting pandas (from ont-remora)
  Using cached pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
Collecting pod5>=0.2 (from ont-remora)
  Using cached pod5-0.2.4-py3-none-any.whl.metadata (20 kB)
Collecting pysam>=0.20.0 (from ont-remora)
  Using cached pysam-0.22.0.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [163 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      # pysam: (sysconfig) CC=gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/
      # pysam: (sysconfig) CFLAGS=-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
      # pysam: (sysconfig) LDFLAGS=-L/Users/keenhl/miniconda3/envs/remora_2_1_b/lib -Wl,-rpath=/Users/keenhl/miniconda3/envs/remora_2_1_b/lib -Wl,--no-as-needed -Wl,--sysroot=/
      checking for gcc... gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/ accepts -g... yes
      checking for gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/ option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking how to run the C preprocessor... gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/ -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking whether _XOPEN_SOURCE is declared... no
      checking C compiler flags needed for ssse3... -mssse3
      checking C compiler flags needed for popcnt... -mpopcnt
      checking C compiler flags needed for sse4.1... -msse4.1
      checking C compiler flags needed for avx2... -mavx2
      checking C compiler flags needed for avx512f... unsupported
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... no
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      configure: error: libbzip2 development files not found
      
      The CRAM format may use bzip2 compression, which is implemented in HTSlib
      by using compression routines from libbzip2 <http://www.bzip.org/>.
      
      Building HTSlib requires libbzip2 development files to be installed on the
      build machine; you may need to ensure a package such as libbz2-dev (on Debian
      or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
      is installed.
      
      Either configure with --disable-bz2 (which will make some CRAM files
      produced elsewhere unreadable) or resolve this error to build HTSlib.
      checking for gcc... gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/ accepts -g... yes
      checking for gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/ option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking how to run the C preprocessor... gcc -pthread -B /Users/keenhl/miniconda3/envs/remora_2_1_b/compiler_compat -Wl,--sysroot=/ -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking whether _XOPEN_SOURCE is declared... no
      checking C compiler flags needed for ssse3... -mssse3
      checking C compiler flags needed for popcnt... -mpopcnt
      checking C compiler flags needed for sse4.1... -msse4.1
      checking C compiler flags needed for avx2... -mavx2
      checking C compiler flags needed for avx512f... unsupported
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... no
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      configure: error: libbzip2 development files not found
      
      The CRAM format may use bzip2 compression, which is implemented in HTSlib
      by using compression routines from libbzip2 <http://www.bzip.org/>.
      
      Building HTSlib requires libbzip2 development files to be installed on the
      build machine; you may need to ensure a package such as libbz2-dev (on Debian
      or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
      is installed.
      
      Either configure with --disable-bz2 (which will make some CRAM files
      produced elsewhere unreadable) or resolve this error to build HTSlib.
      Makefile:142: htscodecs.mk: No such file or directory
      config.mk:2: *** Resolve configure error first.  Stop.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "/Users/keenhl/miniconda3/envs/remora_2_1_b/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/keenhl/miniconda3/envs/remora_2_1_b/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/keenhl/miniconda3/envs/remora_2_1_b/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/localscratch/pip-build-env-432k4z7b/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/localscratch/pip-build-env-432k4z7b/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/localscratch/pip-build-env-432k4z7b/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/localscratch/pip-build-env-432k4z7b/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 442, in <module>
        File "<string>", line 82, in run_make_print_config
        File "/Users/keenhl/miniconda3/envs/remora_2_1_b/lib/python3.7/subprocess.py", line 411, in check_output
          **kwargs).stdout
        File "/Users/keenhl/miniconda3/envs/remora_2_1_b/lib/python3.7/subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by marcus1487** [comment]
This is definitely a pysam installation issue and not a remora issue. Could you confirm that you can install pysam (`pip install pysam==0.22`) in this exact same environment? It would be quite odd if pysam install via remora fails, but installation of pysam alone is successful.

**Comment by keenhl** [comment]
Thanks for your help. You are completely correct about pysam being the problem.  The version of pysam installed is  0.15.3. This was installed via conda install pysam.  When I try to install via pip install pysam==0.22, there is an error.  So, this is the error I need to figure out.  I will close this for now and when I get the install of pysam 0.22 figured out,I will come back and provide an update.
