### ISSUE TITLE
Base modification detection for direct RNA sequencing 

### ISSUE THREAD

**Issue by keenhl** [nanoporetech/remora#124]
Are there any models available for base modification detection for direct RNA sequencing?

**Comment by marcus1487** [comment]
We have an m6A model which we are hoping to release very soon for the RNA004 chemistry, but this has not been released at this time. I will update this issue when this model has been released.

**Comment by keenhl** [comment]
Thanks.  We are interested in 5mC for the RNA002 chemistry.

**Comment by marcus1487** [comment]
We are not actively developing RNA modified base models for RNA002. An RNA 5mC model for RNA004 is not currently in progress internally. I would recommend that you have a look at the [Betta developers program](https://community.nanoporetech.com/posts/betta-tool-release) if you'd like to have a go at training your own model.

**Comment by marcus1487** [comment]
m6A model was added in release v3.0.0. We do not have current plans to release a 5mC model at this time so I will close this issue.

**Comment by keenhl** [comment]
Thanks for the information.
