### ISSUE TITLE
Non SAM mod base abbreviation support?

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/remora#125]
Quick question, is non-samtag modified base abbreviation available yet? As I understand, only 4 cytosine abbreviations were supported a while ago with one of them (5fC) not working at all. Is there a workaround?

**Comment by marcus1487** [comment]
We are working on getting ChEBI code support throughout (and mostly allowing any code within remora). Is there a specific command/functionality for which you were looking for support?

**Comment by jorisbalc** [comment]
It's mainly a QoL option, since we're working with plethora of different modifications and training remora models to identify them. I'm glad to hear about the upcoming ChEBI support.
