### ISSUE TITLE
training your own model

### ISSUE THREAD

**Issue by AlineMuyle** [nanoporetech/remora#127]
I am looking for a detailed pipeline to train my own model of base modification.
I have native DNA sequenced by ONT and BS-seq data for the same sample and I would like to train an all context 5mC model (CG, CHG, CHH).
Do you have code available for the different data preparation steps (including filtering of modified and unmodified cytosines from the BS-seq data)?
Thanks in advance for your help.

**Comment by aCoalBall** [comment]
Hi, @AlineMuyle 

I think you can use ```--focus-reference-positions``` in ```remora dataset prepare```

**Comment by AlineMuyle** [comment]
Thank you for your answer @aCoalBall do you know how to make it take the different contexts (CG, CHG, CHH) into account separately?
It would be really nice if the ONT team could provide a pipeline to do that because I think it would be of interest to many people. I find it hard at the moment to understand how to run remora because of the lack of documentation and pipeline, but maybe I missed it?
Thanks a lot

**Comment by marcus1487** [comment]
Hi @AlineMuyle , In what way would you like to take the different contexts into account?

In terms of a pipeline, after basecalling (with the appropriate options; move table, MD tag etc) the "pipeline" consists of two commands: `remora dataset prepare` and `remora model train`. These commands are outlined in the README and all options are documented on the command line (use `-h` option). If there are details lacking here I'd be happy to update these where appropriate (or answer specific questions here). We do have a new release coming shortly which has some minor updates to model data prep and training, but largely the steps remain the same.

As @aCoalBall noted the `--focus-reference-positions` option is likely your best bet. But I would caution that we do not include native data in release models as the labels are fuzzy (percentages at reference locations). For production models we produce randomer data ([find out more here](https://community.nanoporetech.com/posts/betta-tool-release)) where modified base labels are 100% known. You might have some luck training a model from native sites where alternative methods show completely canonical or modified reads, but I would guess that it will be hard to come by 100% modified sites in CH contexts. Annotating these sites for high quality training data is one of the main reasons we have moved away from native training data. 

I hope this is helpful, but please do comment with any further specific quesitons.

**Comment by AlineMuyle** [comment]
Dear @marcus1487
Thank you for your answer it is very useful.
So I understand it is not the best to train a model with DNA that is not 100% methylated or 100% unmethylated. I might try it anyway because I have pore 9.4.1 plant data with DNA methylation in all contexts. I tried basecalling  with model res_dna_r941_min_modbases-all-context_v001 and obtained poor correlation of ONT inferences to BS-seq data (R2 0.4). I am hoping that with a newly trained model I might obtain higher correlation between ONT and BS-seq. Or is there a pore 9.4.1 all context 5mC model that I am not aware of that could fit my data better?

Are you thinking in future to allow model training while allowing native methylation? I mean, intermediate methylation proportions? Or is this not doable, too complicated to properly train?

**Comment by marcus1487** [comment]
> So I understand it is not the best to train a model with DNA that is not 100% methylated or 100% unmethylated. I might try it anyway because I have pore 9.4.1 plant data with DNA methylation in all contexts.

I think the biggest issue here is that a fully methylated sample is not really all-contexts, but instead contexts where all bases are swapped out. To be specific the 5-mer context CACGC has the central C base and two flaking C bases. The "context" of identifying whether the C in the center is 5mC or canonical C is effected by the C at the other two positions. Observing the signal levels when all 3 are modified does not translate well to the, often much more common, case when only the central base is modified. Not to say there is not some value here, but I would not recommend counting on this method to work.

> I tried basecalling with model res_dna_r941_min_modbases-all-context_v001 and obtained poor correlation of ONT inferences to BS-seq data (R2 0.4).

I do not doubt that the results may not be sufficient for your research as this is a research grade model, but I would recommend that judging correlation values (especially compared to CG-context results) should be avoided. CH context methylation is generally quite low and correlation with a low dynamic range (or ever in this case) is not a good metric. I would recommend RMSE as a better metric for comparing models using aggregated metrics.

> Or is there a pore 9.4.1 all context 5mC model that I am not aware of that could fit my data better?

We do not have another R9 all-context 5mC model. Best recommendation here is to upgrade to R10 series pore for the best results.

> Are you thinking in future to allow model training while allowing native methylation? I mean, intermediate methylation proportions? Or is this not doable, too complicated to properly train?

It is possible to prepare training data from Remora using native data with appropriate data processing. We do not currently have the pipelines built for this and we are not likely to do so as randomer data training has proven to work better with a much simpler data processing workflow. For previous flip-flop models we did have this pipeline implemented, but as you can see from the results of the released all-context model the results were not up to par with the models produced with randomer training data. This data preparation was indeed likely too complicated for wider use to obtain a high quality model. I would recommend that this is not likely to produce the highest quality results. Again the recommendation here would be to upgrade to the R10 series pore.

I hope this is at least somewhat helpful and please do reach out if you have any other specific questions.
