### ISSUE TITLE
Can Models Be Generalizable Across Sampling Rate 

### ISSUE THREAD

**Issue by andrewgalbraith21** [nanoporetech/remora#128]
Hello!

I have trained a model on Kit 10 V14 Chemistry with a sampling rate of 4KHz. We are now upgrading our software for 5KHz sampling rate. I am wondering can a model be made generalizable to sampling rate. Or is it necessary to sequence the data again on 5kHz to retrain a model? 

All the best,
Andrew Galbraith

**Comment by marcus1487** [comment]
Models trained on alternative conditions will run within current software offerings, but generally show a regression against new conditions. The scale of this regression depends on many factors. For production model we always train (or finetune) models using the new condition. The requirement for re-training depends upon your requirements of the model and acceptable regression in model performance. Overall my suggestion would be to test any new combination of model and condition and in general I would recommend matching training and deployment conditions as closely as possible.

**Comment by andrewgalbraith21** [comment]
Hello @marcus1487 makes sense thanks for the quicky reply
