### ISSUE TITLE
Using pre-trained models for feature extraction

### ISSUE THREAD

**Issue by parham-k** [nanoporetech/remora#129]
Hi! I am interested in using one of Remora's intermediate layers' output as a feature extraction step for my own project. I can see that Remora models are exported as `RecursiveScriptModule`s in TorchScript. Since adding hooks is not supported in TorchScript modules (see [this issue](https://github.com/pytorch/pytorch/issues/29037#issuecomment-792868448) and [this discussion](https://discuss.pytorch.org/t/register-forward-hook-is-not-supported-on-scriptmodules/57009)), I was wondering if you could please help me achieve this.

**Comment by marcus1487** [comment]
Your best bet is probably to load the model from the python module (or the portion of the module required for your task) and manually transferring the required layers over from the trochscript model. Most all Remora models (except for some very early ones) use [this python module](https://github.com/nanoporetech/remora/blob/master/models/ConvLSTM_w_ref.py) for the model structure. So you could load the model via: 
```
from remora import model_util
model = model_util._load_python_model("/path/to/remora/models/ConvLSTM_w_ref.py", {
        "size": [size],
        "kmer_len": [kmer_len],
        "num_out": [num_labels],
    })
```
This object should allow much more manipulation than the trouchscript model, which is indeed optimized for inference speed.

Currently extracting the size, kmer_len and num_out is a bit cumbersome, but the next Remora release will have a helper function `_raw_load_torchscript_model` which will make extracting this information much easier. i'm hoping to get this release out this week.

**Comment by parham-k** [comment]
Thanks @marcus1487! Looking forward to the next releases :)

**Comment by marcus1487** [comment]
The new release is now out. Please re-open this issue if you encounter any further issues.
