### ISSUE TITLE
remora model with multiple modifications

### ISSUE THREAD

**Issue by hd2326** [nanoporetech/remora#13]
Greetings!

I'm wondering whether remora models can handle multiple modifications at the same time. For instance a model that can predict 5mC and 6mA simultaneously. It seems not since the {--motif, --mod-bases} pair can only represent one modification per model. Any plans for upgrading remora for handling multiple modifications?

Thank you very much!

**Comment by marcus1487** [comment]
The plan is to have a single Remora model handle all alternatives to a canonical base that one desires to call simultaneously. So to call 5mC and 6mA simultaneously would require two Remora models. This should be supported in Guppy with the latest release (though the only released Remora models are cytosine-alternatives). Bonito and Megalodon do not currently support loading multiple Remora models, but may add this support in the future (likely once we have released a 6mA model).

**Comment by hd2326** [comment]
@marcus1487 Got it! Thank you so much for the clarification!

**Comment by marcus1487** [comment]
The latest Guppy release (6.1.1 released today) now supports Remora models (see `remora/scripts/convert_onnx_to_ont_json.py` to convert user trained models). MinKNOW support for Remora models is also in the works (see Clive's tech update talk from earlier today). Currently only 5mC and 5mC+5hmC in CG contexts are supported, but we are hard at work to expand this offering. New models will be first shipped with Remora in this repo and then incorporated into our production basecallers once they have been fully validated.

**Comment by hd2326** [comment]
Sounds great! Thank you so much @marcus1487 !
