### ISSUE TITLE
Modified basecalling for supplementary alignments

### ISSUE THREAD

**Issue by e-sollier** [nanoporetech/remora#131]
Hi,

I processed some samples with the epi2me human variation workflow, calling methylation using the dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2 model. I noticed that for supplementary alignments (with flag 2048), the methylation calls do not overlap with CpG sites, and are generally different from the methylation state of neighbouring CpG sites for other reads (see the reads at the bottom of the following figure):
![methylation_supplemenatary_alignments](https://github.com/nanoporetech/remora/assets/33619615/2a7708a8-a07a-4faf-a85b-47fa51a98382)

From #106 it looks like supplementary alignments are not processed by remora. Is there a fundamental reason why they are ignored, or would it be possible to consider them as well ? 
Even if no methylation calls are made for supplementary alignments, then why do I see some when visualizing the reads in IGV ? I noticed that in the human variation workflow, dorado generates a bam file, [which is then converted back to fastq and realigned with minimap2 ](https://github.com/epi2me-labs/wf-human-variation/blob/93a02af3ffb14834320f1f006a8a133d84f26520/workflows/_basecalling.nf#L43). I wonder whether that might be causing some issues with supplementary alignments ?

Thanks in advance for your help!

**Comment by marcus1487** [comment]
Supplementary alignments from minimap2 unfortunately contain hard clipped bases. Due to the structure of the modified base tags this renders the modified base tags un-usable without the primary mapping containing the full SEQ field. So this is the fundamental reason that Remora does not processing supplementary alignments. Processing would require some much more complex engineering, requiring an indexing step on the BAM file to allow the program to jump around the BAM file or storage of all SEQ fields in memory drastically increasing RAM usage of commands. 

The fact that IGV attempts to visualize these modified base calls feels like a bug to me. The modified base tags for the read are not valid, so outputting modified base calls on a read with hard clipping should not happen. It would be good to log this issue with IGV (or test if this is still the case on the latest version of IGV).

**Comment by e-sollier** [comment]
Thanks for the reply! 

I understand that hard clipping would make the MM tag unusable. But if minimap2 could output soft clipped supplementary alignments then remora could in principle process them ? I have just read through the minimap2 documentation and there is apparently a -Y option to use soft clipping for supplementary alignments! Would it be possible to implement this in remora/dorado ? It would be nice to have modified basecalls also for supplementary alignments.

Concerning IGV, you mean that IGV should ignore modified basecalls if the read contains hard clipping? I see your point and I will check if the latest IGV version does it, but regardless, shouldn't remora simply remove the MM and ML tags from supplementary alignments if they are not usable ? Otherwise there will always be the risk that downstream tools (IGV or other) don't check for hard clipping and misinterpret the modified basecalls.

**Comment by marcus1487** [comment]
> Would it be possible to implement this in remora/dorado ?
Could you elaborate on what specifically you would like implemented here? Would you like the `-Y` minimap option exposed in dorado? If so you might open that issue in the dorado issues. Is there something specific you'd like added to remora support for supplementary alignments?

> shouldn't remora simply remove the MM and ML tags from supplementary alignments if they are not usable ?
Remora does not produce supplementary alignments or process supplementary alignments for modified base calling. Minimap produces these alignments (potentially from Remora modified base calls). It would make some sense for modified base calls to be removed from alignment output in dorado. Again this feature could be raised in dorado. For minimap passing modified base calls through to mappings this can be controlled with the `-T` flag to `samtools fastq` specifying which tags you'd like passed forward into minimap. I don't think there is any thing for standalone minimap to implement here (and potentially a part of the reason minimap developers may have chosen to decline adding support for SAM/BAM input.

If there is something else that you'd like implemented/supported here please elaborate on the specific feature/output you'd like to have enabled.

**Comment by e-sollier** [comment]
Thanks for the information. Yes, basically I would like the -Y minimap option to be exposed in dorado, or even be the default.
I was initially a bit confused about the different steps done by dorado (basecalling, modified basecalling, alignment): when I read in #106 that remora did not process supplementary alignments, I somehow assumed that remora would be run after the alignment. But as I understand it now, the modified basecalling is performed before the alignment (which indeed makes more sense), so the supplementary alignments do have methylation calls, but they just need the full sequence information (for example with soft clipping) to make those methylation calls interpretable.
So I do not need any new feature from remora, I will create issues in the more appropriate repos.

Thanks!
