### ISSUE TITLE
how to distinguish 5mC and 5hmC

### ISSUE THREAD

**Issue by luming-zou** [nanoporetech/remora#132]
The remora provided 5hmC_5mC and 5mC models, but, how to distinguish 5mC and 5hmC base modification from the results? 'm' is single modified base code, what is the single modified base code for  5hmC? If 5hmC and 5mC are all marked as 'm', can I do the analysis using 5mC model and 5hmC_5mC model separately and then compare the results to obtain 5hmC sites?

**Comment by marcus1487** [comment]
5hmC uses the `h` single letter modified base code as defined in the [SAM tags specification document](https://samtools.github.io/hts-specs/SAMtags.pdf). You can use a single BAM file containing 5mC and 5hmC calls to analyze both modifications. Please see the [modkit package](https://github.com/nanoporetech/modkit) for our available downstream processing steps.

**Comment by luming-zou** [comment]
Than you very much for replying. If so, it means no 5hmC were detected from my data. My data was sequencing of fall armyworm mid-gut DNA on PromethION, with R9.4.1 flow cell and SQK-LSK109 kit.
