### ISSUE TITLE
RemoraError: Move table discordant with signal

### ISSUE THREAD

**Issue by alexcritschristoph** [nanoporetech/remora#135]
I'm walking through the tutorial on my own data like so and am getting an error nobody seems to have gotten before.

Code:
```
pod5_dr = pod5.DatasetReader('raw/LIB61')
bam_fh = io.ReadIndexedBam("lib61.map.bam")

read_id = "06dcfad2-630e-4b6f-884e-4f95653faebb"
pod5_read = pod5_dr.get_read(read_id)
bam_read = bam_fh.get_first_alignment(read_id)
io_read = io.Read.from_pod5_and_alignment(pod5_read, bam_read)
```

And in running that last line I get the error:
```
File ~/.local/lib/python3.10/site-packages/remora/io.py:396, in parse_move_tag(mv_tag, sig_len, seq_len, check, reverse_signal)
    391 if check and mv_table.size != sig_len // stride:
    392     LOGGER.debug(
    393         f"Move table (len: {mv_table.size}) discordant with "
    394         f"signal (sig len // stride: {sig_len // stride})"
    395     )
--> 396     raise RemoraError("Move table discordant with signal")
    397 return query_to_signal, mv_table, stride

RemoraError: Move table discordant with signal
```

I don't get this error on the test data from remora, so it must be some issue with my data. 
I have tested a dozen or so different reads in my BAM file and I get the error with every read. 

It was produced by dorado like so:
```
/home/cultivarium/dorado-0.4.1-linux-x64/bin/dorado basecaller /home/cultivarium/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 $library_name --emit-moves --modified-bases-models /home/cultivarium/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2,/home/cultivarium/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v3 > $library_name.d3.bam
```

and then mapped to the ref with minimap2 like so:
```
samtools fastq dorado_output.d3.bam -T mv,MM,ML | minimap2 -t 14 --MD --secondary=no -ax map-ont -y ref.fasta - | samtools view -s 0.027 -b | samtools sort -@ 10 -o lib61.map.bam
```

Some extraneous points:
1. My POD5 files were originally output by MinKNOW (and were basecalled using guppy at the time- I doubt this is relevant but just checking)
2. There are more reads in my directory of POD5 files than in my BAM (can't imagine it matters but just checking).
3. I have a few different bams produced in an identical fashion, all have this same error
4.  The BAM does have the mv and MD tags.
5.  The reference is very small (circular plasmid).
6.  Data is from Flongle.

**Comment by marcus1487** [comment]
Can you set the log file (`remora.log.init_logger("/path/to/log.txt")`) and report the output? This may be related to split read processing, but I've not seen this issue yet. If you could also pass a very small bam file (just a couple of reads would do and they don't need to be mapped) that would help in diagnosing the issue.

**Comment by alexcritschristoph** [comment]
So here's the log - I see it's sparse...

[remora_log.txt](https://github.com/nanoporetech/remora/files/13395359/remora_log.txt)

Link to a subsampled bam with a few reads:

https://drive.google.com/file/d/1DgWmeTjS8Fzgzldd7o1UEZ0416pBsmjQ/view?usp=sharing

**Comment by marcus1487** [comment]
This does look like an invalid move table. Could you try to use the most recently updated Dorado version to see if this has been resolved? v4.3 was released just this Wednesday and may resolve this issue.

**Comment by alexcritschristoph** [comment]
So far this seems to be fixed with Dorado 0.5. Will re-open if I run into it again

**Comment by alexcritschristoph** [comment]
So I actually have run into this again with Dorado 0.5, and I think I have figured out a bit more about where the problem comes from. I do not get this error when my bam is unmapped, but after mapping the same BAM:

```
samtools fastq sample.bam -T mv | /usr/bin/minimap2 -t 14 --secondary=no -ax map-ont -y ref.fasta - | samtools view -b > sample.map.bam
```
I'm on samtools 1.19 and minimap2 2.26-r1175.

**Comment by alexcritschristoph** [comment]
Interestingly, the alternative mapping command below (from remora wiki) resolves the above. Not sure why.

```
samtools fastq -T "*" sample.bam | /usr/bin/minimap2 -y -ax ref.fasta - | samtools view -b -o sample.map.bam
```
