### ISSUE TITLE
make_config not found

### ISSUE THREAD

**Issue by yifengyuan** [nanoporetech/remora#142]
Hi,

I am using remora version 2.1.3. I installed it from pip with

`pip install ont-remora`

I did remora dataset prepare, however I stucked with make_config command.

```
remora dataset make_config
usage: remora dataset [-h] {prepare,split,merge,inspect} ...
remora dataset: error: invalid choice: 'make_config' (choose from 'prepare', 'split', 'merge', 'inspect')
```
It seems that my remora does not have the make_config command.

Please advise me. Thank you.

**Comment by marcus1487** [comment]
The `make_config` command was added in Remora 3.0. Please upgrade to use this feature. Note that you will also have to upgrade your datasets to the new Remora 3.0 dataset format with the update script included in the repository. See the README for instructions on this. Please re-open this issue if you experience any issues with this.
