### ISSUE TITLE
the exact input length of remora model？

### ISSUE THREAD

**Issue by xieyy46** [nanoporetech/remora#147]
Hi remora developer,
I am studying Remora, but I have encountered some questions about the input and structure of the Remora model. In the 'Remora dataset prepare' step, we can specify the size of the chunk through the parameter --chunk-context. I want to know if the size of the chunk is the same as the length of the input to the Remora model. In other words, will the entire raw signal of the chunk be input, or is only a portion extracted around the focus_bases?

**Comment by marcus1487** [comment]
In Remora 3.0 the chunk size can be modulated at the time of training, but cannot be larger than the value set at data preparation time. In previous versions of remora it was required that the chunk size was defined at data preparation time. 

The defined chunk size set at training time is the exact input length of the signal input into the Remora model. The focus base is the base of interest being called as modified or not. There is no concept of multiple focus bases for a Remora model (not sure if the multiple was a typo or not). The sequence input into the model is defined as a k-mer. Thus at the last signal point included in the chunk the sequence input into the model extends by the number of bases defined by the --kmer-context-bases argument. 

I hope this helps, but if you have further questions please elaborate and I'd be happy to assist further.

**Comment by xieyy46** [comment]
Hi marcus,
Thank you for your reply! By the way, I want to know how much data you used to train the current remora 5mC model. How many chunks?

**Comment by marcus1487** [comment]
The most recent models are trained from a variety of sources including neighboring sites to other modified bases, PCR and native datasets as well as many more. Some datasets are sampled from at a shallow depth so the total number of chunks supplied to training may not be near the number actually presented to the model. In total though, the most recent models were trained from over 1 billion training examples.

I'm not sure if you were looking for the exact number used to train a specific model, but we are not likely to release such exact figures. We have found that training from 20-50 million chunks can produce quite good (release quality) models and that, for many purposes, good models can be trained from as few as a couple million training chunks. I hope this helps and please comment if any further clarification would be helpful.
