### ISSUE TITLE
Question: How to change modification names in model after training?

### ISSUE THREAD

**Issue by hengjwj** [nanoporetech/remora#148]
Hi, 

I trained a model following the documentation but along the way used the wrong names (both short and long) for the modification. Is there a way to change this without re-training the model? Which are the files which would need to be updated with the correct name?

Thanks in advance!

Joel

**Comment by marcus1487** [comment]
If you are using dorado the config.toml would be the easiest way to adjust the modified base names. 

If you need the PyTorch format model, the 
`_raw_load_torchscript_model` and  `_extract_essential_metadata` functions allow you to extract the data required to save a new model (after appropriate adjustments). I can provide a more complete solution after the holidays break.

**Comment by marcus1487** [comment]
Did this resolve your issue?
