### ISSUE TITLE
remora dataset prepare not support r9.5 chemistry?

### ISSUE THREAD

**Issue by xieyy46** [nanoporetech/remora#150]
Hi remora team,
I tried to run remora dataset prepare for my reads sequenced in r9.5 chemistry, but got error as shown below.
![image](https://github.com/nanoporetech/remora/assets/76148123/0cdf4fbc-a0cb-4a01-9a97-e1d77f4ce57b)
 
I noticed that the mv tag in the  r9.5 bam file is different from that in both r9.4.1 and r10.4.1 bam file.

the command line:
remora dataset prepare test.pod5 test.bam --output-path remora --motif TC 0 --mod-base-control --kmer-context-bases 2 3 --max-chunks-per-read 5000

**Comment by marcus1487** [comment]
I cannot access your attached image. I am also not aware of any r9.5 chemistry. Are you referring to RNA4 data? Could you please post the exact error that you are receiving (in text) and also explain in more detail what you mean by "I noticed that the mv tag in the r9.5 bam file is different from that in both r9.4.1 and r10.4.1 bam file."?

**Comment by xieyy46** [comment]
Hi,
R9.5 is an old version of Nanopore chemistry, and my reads were produced using an R9.5 flow cell several years ago.

I basecalled my reads using dna_r9.5_450bps.cfg  and then align to reference genome:
guppy_basecaller -i pod5 -s outdir -c dna_r9.5_450bps.cfg  --moves_out  --bam_out
dorado aligner reference.mmi calls.bam --secondary no -t 20 > calls_aligned.bam

I tried to prepare remora dataset:
remora dataset prepare convert.pod5 calls_aligned.bam  --output-path remora --motif T 0 --mod-base-control --kmer-context-bases 2 2 
but found that all my reads in the bam files got "Move table discordant with basecalls"
![image](https://github.com/nanoporetech/remora/assets/76148123/fb947d07-d50b-491d-a0b7-5036274e00cb)

I noticed that the mv tag in my bam file (basecalled using dna_r9.5_450bps.cfg) is is different from that in both r9.4.1 and r10.4.1 bam file:
![image](https://github.com/nanoporetech/remora/assets/76148123/be532857-36c6-499a-8ee6-a58d31ff6735)

**Comment by marcus1487** [comment]
The issue here is that the move table does not correspond to the basecalls and signal for this read. Thus there is nothing that Remora can do to process these reads and produce training data. If you could raise this issue with the basecalling algorithm (and ideally update to Dorado which would provide the fastest support) that would be the best way to proceed.
