### ISSUE TITLE
Alternative model

### ISSUE THREAD

**Issue by philipmories** [nanoporetech/remora#152]
Hello,
I would like to ask if, in the absence of a reference sample without modifications, I can still use the program for methylation detection. Is there perhaps some alternative model in this case? Tombo had such an option.

**Comment by marcus1487** [comment]
The analog to the alternative model from Tombo in Remora is the Remora model. This is no longer a k-mer level model, but instead is a neural network taking in the signal at the basecalled position of the base of interest. It is still possible to derive a set of levels for a known modification using the Remora signal processing API, but given the vastly improved modified base accuracy of the neural network approach we are no longer making alternative k-mer level (alternative) models a primary target. If you have a specific application which requires the alternative k-mer levels please specify more details of this application and we'd be happy to assist further.
