### ISSUE TITLE
Is mapping necessary to train my model?

### ISSUE THREAD

**Issue by moa4020** [nanoporetech/remora#154]
Hi Marcus, 

I have generated a randomer dataset to represent the base-modification 8-oxoG in all possible contexts.
The 35-nt oligo sequences are concatenated end-to-end in this pattern: left-handle-NNNNNN**G**NNNNNN-right-handle or left-handle-NNNNNN**o**NNNNNN-right-handle (o: 8-oxoG). Left and right handles are constant recognizable sequences across all oligos. N is a degenerate base, meaning the focus base is surrounded by a random 6-mer on either side. 

Since the longer the sequences, the better the accuracy, I decided to concatenate these 35-nt oligo sequences end to end and sequenced the ssDNA. I have no idea of how to generate a reference fasta file for this because my sequences vary in size from 35 nts to 300 nts. I was wondering if creating a reference fasta file is necessary to use remora and train a model to detect single occurrences of 8-oxoGs?

I am able to generate the .bam files from the .pod5 files with --emit-moves option on dorado. But I have no idea how to add the --MD tag to the bam file. Any suggestions how I can make that happen? Do I generate a reference fasta sequence with all possible sequences for this pattern: "left-handle-NNNNNN**G**NNNNNN-right-handle" and map my sequences to this reference fasta? Won't I have to generate a reference file for all multiples of the oligo? eg (n=35 nts): n, 2*n, 3*n, 4*n, 5*n .... 8*n, 9*n?  

This is a bit overwhelming, any advice/suggestion appreciated.

**Comment by marcus1487** [comment]
This is certainly a unique sample type. We do not have a standard processing pipeline for this type of sample as we do not recommend this sample for the training of Remora models. If you are looking for the recommendation for all-context model training data I would suggest you have a look at the [Betta developer program](https://community.nanoporetech.com/posts/betta-tool-release). 

Without access to Betta I would recommend creating a custom processing pipeline for this specific sample type. The Remora API will allow you to process the basecalled reads and extract the chunks are required, but identifying the modified base positions of interest will require custom processing that we are not likely to support in the near term. I hope this helps and please do reach out if you have specific questions about how to use the Remora API in this setting.

**Comment by moa4020** [comment]
Hi @marcus1487, thank you for your response. We've been trying to get access to the Betta developer program. Is there a user license for researchers to just use the tools on the package instead of a developer's license?

**Comment by marcus1487** [comment]
Access to Betta code is restricted to users with the developer's license at this time.
