### ISSUE TITLE
How/where to get prediction probablilities to plot ROC/PR curves?

### ISSUE THREAD

**Issue by hengjwj** [nanoporetech/remora#155]
Hi,

I've looked in the repo but I only managed to find a method to validate the model (validate from_modbams). 

How/from which file(s) do I extract the probabilities to plot the ROC and PR curves? 

Thank you!

Joel

**Comment by marcus1487** [comment]
The best for this would be to use the `modkit extract` command to extract the modified base calls from BAM files. We are currently working on porting the validation command from remora over to modkit as well.

**Comment by hengjwj** [comment]
Thanks for pointing me to it!
