### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by DiegoZavallo** [nanoporetech/remora#16]
Hi, I´m new to the ONT technology analsyis and before I get into it I was wondering if remora could be used to detected methylated bases on plants (meaning that also detects other Cs contexts like CHG and CHH)
I read about DeepSignal-Plant which supposedly was designed for that kind of context

I want to know if it suits for my type of data (plants)

Thanks

Diego

**Comment by marcus1487** [comment]
We do not currently have a released all-contexts (so including CHH and CHG contexts) 5mC model released, but this is high on our priority list. I will post here once this model is released.

**Comment by DiegoZavallo** [comment]
thanks, marcus!
looking forward to the new release!

**Comment by marcus1487** [comment]
Answered in [megalodon issue](https://github.com/nanoporetech/megalodon/issues/289#issuecomment-1270799025). But no timeline for R9 all-context Remora models at this time.
