### ISSUE TITLE
Possible to call 4mC, 5mC, and 6mA?

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/remora#162]
Hello,

I was wondering if it would be possible to separately use the 4mC+5mC, and 6mA models go get all context modifications for all three from the sequencing data and ideally into the same BAM.

**Comment by marcus1487** [comment]
Yes. Dorado accepts the `--modified-bases-models` argument. The path to multiple comma separated models can be passed to this option to run the 4mC+5mC and 6mA models simultaneously. Remora infer does not currently allow this option, but this should be available in the next release.

**Comment by Flower9618** [comment]
Hello, @marcus1487. Thanks so much for your reply. How about the performance for 5hmC, 4mC and 6mA prediction?
