### ISSUE TITLE
Urgent Help Required: Regarding Error for modified basecalling

### ISSUE THREAD

**Issue by PRIYANKA-22091995** [nanoporetech/remora#163]
I was trying to run the following command for modified basecalling:
 guppy_basecaller -i /DATA/BioLab/Priyanka/FAST5/EB_EL_FAST5/fast5/ -s /DATA/BioLab/Priyanka/FAST5/ -c /home/arnav/workspace/rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.cfg --recursive -a /home/arnav/workspace/PlasmoDB-61_PvivaxSal1_Genome.fasta  --bam_out -x cuda:0 -m /home/arnav/workspace/rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.jsn --barcode_kits EXP-NBD104

But got the below error.

<img width="943" alt="guppy error" src="https://github.com/nanoporetech/remora/assets/109784286/fcadbb40-f873-4cb6-a670-1e6528ea8e28">

**Comment by marcus1487** [comment]
Unfortunately the Guppy implementation is not directly related to the Remora code base. I would suggest trying to upgrade to R10 and dorado where support will be much more active. If you need help with this Guppy command, I would recommend reaching out to customer service or the community page to log this issue.
