### ISSUE TITLE
Accuracy about Remora

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/remora#17]
Hi, thank you very much for sharing this useful tool.

I try to use Megalodon to call base modification, but I find it is very slow. Because when running 'call base modification' step within Megalodon, it will load the specific remora model once I set this, I have an idea that I can run Remora directly if I just want to call base modification for my sample, and the accuracy will be similar to Megalodon, is it right?

**Comment by cjw85** [comment]
Remora is technology demonstrator, the recommended (and simplest) way to call base modifications is to use the latest version of the Guppy basecaller with the options for modified basecalling and alignment turned on. This will give you directly a BAM file annotated with base modification information.
