### ISSUE TITLE
Parser Errors Handling Optimizer or Scheduler Arugment

### ISSUE THREAD

**Issue by andrewgalbraith21** [nanoporetech/remora#176]
Hello,

When inputting either scheduler (i.e. --lr-scheduler StepLR --lr-scheduler-kwargs step_size 3 int --lr-scheduler-kwargs gamma 0.25 float) or optimizer arugments (i.e. --optimizer-kwargs weight_decay 0.00005 float), I get the following error using remora 3.2: 

  File "{path}/argparse.py", line 1030, in __call__
    items.append(values)
AttributeError: 'tuple' object has no attribute 'append'

Interestingly, when I delete the default lines from the parser script (i.e. default=constants.DEFAULT_OPT_VALUES,  and default=constants.DEFAULT_SCH_VALUES,), the code works.

I am wondering is this is a bug or if I am inputting the values incorrectly?

All the best,
Andrew Galbraith

**Comment by marcus1487** [comment]
It looks like this is a bug in argparse [logged here](https://github.com/python/cpython/issues/60603). I will add a workaround to allow user specified arguments in the next version of remora.

**Comment by marcus1487** [comment]
This should be fixed in the 3.2.2 release.
