### ISSUE TITLE
Remora dataset prepare: shuffling

### ISSUE THREAD

**Issue by hengjwj** [nanoporetech/remora#186]
Hi Marcus, I wish to clarify this argument in the documentation:

`--skip-shuffle`

`Skip shuffle of completed dataset. Note that shuffling requires loading the entire signal array into memory. If dataset is very large and shuffling is not required specify this flag. (default: False)
`

Based on what is described, am I right in saying that a large dataset does not require shuffling? What are the implications of not shuffling during this step? 

Thank you!

Joel

**Comment by marcus1487** [comment]
TL;DR Shuffling is not necessary, but may present issues for particular edge cases.

Shuffling may not be necessary. The main issue is that chunks from the same read will be grouped together at writing. Thus these will be read out together during training. Thus it is possible that some unstable training may result from a small subset of poor quality reads. The reason to add the option to this command is that shuffling must load the whole signal array into memory and thus may be prohibitive and can be computationally expensive (though this step has been optimized a bit).
