### ISSUE TITLE
DRS m6A modified bases

### ISSUE THREAD

**Issue by JhinJhinJhin** [nanoporetech/remora#188]
Sorry, I didn't see anything about m6A methylation modification of mRNA. I have fastq files that contain the 'MM' and 'ML' tag, and I would like to know how I should use this software for DRS methylation detection.

**Comment by marcus1487** [comment]
The Remora repository is primarily intended for the preparation of training data and training modified base models. For downstream tasks given modified basecall FASTQ/BAM our modkit tool is the correct place to start. Is DRS differential methylation analysis? Or something else? In any case I would post on the modkit issues if you have trouble finding the correct method within the modkit repo.

**Comment by JhinJhinJhin** [comment]
thanks for your patient answer. And... I have a another question, I have fastq files that contain the 'pt:i' tag, what nanoporetech software can use to polyA downstream analysis.

**Comment by marcus1487** [comment]
I'm not aware of downstream tools that specifically make use of this tag. I believe that the estimated poly-A tail length is now integrated into the actual basecalls in the latest dorado release, but you may post an issue there to confirm. Thus you would not specifically need the `pt` tag, but could use it for easier access to the poly-A tail length. If you can provide the specific downstream task you would like to complete I could try to point you in the right direction for analysis tools.

**Comment by JhinJhinJhin** [comment]
I want to get poly-A tail length for each gene, like nanopolish. But nanopolish need fast5 to be input file, my pod5 cannot be imported into nanopolish as an input file.

**Comment by marcus1487** [comment]
A mapped BAM file should give the mapping location of each read. This can be mapped on to the gene/transcript of interest and then associated with the `pt` tag for that same read. 

I'm not sure what is the exact output which you are trying to replicate from nanopolish. It does seem that this is outside of the scope for Remora at this point though. You might have some luck describing your exact requested output on the Dorado github issues section.
