### ISSUE TITLE
IndexError: list index out of range when running remora dataset prepare due to k-mer table parsing

### ISSUE THREAD

**Issue by iza-mcac** [nanoporetech/remora#190]
Hello,
I'm encountering an error while trying to run the remora dataset prepare command. The issue seems to occur when loading the k-mer table provided (5mer_levels_v1.txt). Below is the command I ran and the traceback of the error:

Command:
```
remora \
  dataset prepare \
  output_pod5s/ \
  output_dorado/calls_nonmod.bam \
  --refine-kmer-level-table /home/izamamede/nanopore_rs/remora/ref/5mer_levels_v1.txt \
  --refine-rough-rescale \
  --motif CG 0 \
  --mod-base-control
```

Error:
```
Traceback (most recent call last):
  File "/home/izamamede/.conda/envs/remora_py38/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/home/izamamede/.conda/envs/remora_py38/lib/python3.8/site-packages/remora/main.py", line 71, in run
    cmd_func(args)
  File "/home/izamamede/.conda/envs/remora_py38/lib/python3.8/site-packages/remora/parsers.py", line 300, in run_dataset_prepare
    sig_map_refiner = SigMapRefiner(
  File "<string>", line 17, in __init__
  File "/home/izamamede/.conda/envs/remora_py38/lib/python3.8/site-packages/remora/refine_signal_map.py", line 294, in __post_init__
    self.load_kmer_table()
  File "/home/izamamede/.conda/envs/remora_py38/lib/python3.8/site-packages/remora/refine_signal_map.py", line 230, in load_kmer_table
    self.kmer_len = len(kmer_fp.readline().split()[0])
IndexError: list index out of range
```
Linux v:   Ubuntu 22.04.3 LTS,  22.04

Could you please investigate this issue? Let me know if you need any further information or files for troubleshooting.

Thanks!

**Comment by marcus1487** [comment]
This error indicates that a row of the kmer levels file does not have any records in the first line. This command (and k-mer level table parsing) has been tested with the file provided with the repository as well as those found in the k-mer repository referenced in the README ([link here](https://github.com/nanoporetech/kmer_models)). Could you confirm that the kmer file you are passing has a valid first line? If this looks in order would you mind testing on one of the kmer models from the kmer_models repository?

**Comment by iza-mcac** [comment]
Hey @marcus1487 thanks for the quick response. I had downloaded that index file directly from there but just checked the header and it somehow had gotten corrupted. Manually copying it from github made it work. Thanks a lot for your help!

**Comment by marcus1487** [comment]
No problem. Glad it was a simple fix! Good luck with your model training!
