### ISSUE TITLE
R10.4 250bps signal to base mapping

### ISSUE THREAD

**Issue by marcpaga** [nanoporetech/remora#26]
I am trying to prepare a dataset for base modification detection that has been sequenced on a MinION device using an R10.4 flow cell at high accuracy mode 250bps.

Checking at the https://github.com/nanoporetech/megalodon/tree/master/megalodon/model_data available models to prepare the data I don't think this model is available yet on megalodon. Should I just wait for the model to be released or is one of these models in megalodon compatible?

Alternatively, I am used to the old fashion tombo resquiggle for R9.4 for base to signal mapping, and I found that remora also does something similar. It refers to a `kmer_model_filename`, but my guess is that this is not open to the public right?

Best,
Marc

**Comment by marcus1487** [comment]
For the basecalling model, and guppy model can be used. The `model_data` directory contains only calibration files for the modified basecalling (from old style flip-flop modified base models) or variant calling. For basecalling, reference mapping and signal mapping this information is not required.

As for the k-mer models, we do not currently have a publicly available release of these for newer pores. It might be possible to bootstrap a kmer model using tombo, but aside from this we do not have public solution to estimate kmer models/levels.
