### ISSUE TITLE
How to use megalodon with ONNX model?

### ISSUE THREAD

**Issue by cvermeulen88** [nanoporetech/remora#27]
Dear authors,

I have followed the guide in the readme to make an onnx model. 
At the end of the guide it is mentioned that:
"This command will produce a final model in ONNX format for use in Bonito, Megalodon or remora infer commands."

However I cannot find any instructions on how to use megalodon with an onnx model. 

The megalodon option --remora-modified-bases seems to be specific for pretrained models, but is there some other option for home-made models? Or is there some other way to convert an onnx model into a useable model for megalodon?

With kind regards,
Carlo

**Comment by marcus1487** [comment]
The option is `--remora-model`. You can see help for many more options in megalodon with the `--help-long` argument.
