### ISSUE TITLE
Running Megalodon for Remora 5mC_all_context_sup_r1041_e82 model

### ISSUE THREAD

**Issue by jcolicchio-soundag** [nanoporetech/remora#31]
We are interested in trying out doing methylation calling on data generated from an R10.4.1 flow cell that has already been basecalled using the SUP basecalling model.

From everything we've read, it seems like this is the exact use for the Rerio model: 5mC_all_context_sup_r1041_e82

I had a few questions about the logistics of actually running this model though. We have successfully downloaded the file and have the .onnx, but im not sure of what we should be using for the following parameters:

Should we use the --do-not-use-guppy-server command if we want to use the basecalling that has already been done and is in our fast5 files?

If not, what should we specify for our --guppy-config file? My intuition is: dna_r10.4.1_e8.2_260bps_sup.cfg, but when we try this it times out without ever starting. When looking at the logs: "Could not load guppy server configuration state: 'Configurations'"

For this rerio model, should we specify --remora-modified-bases?

If this is of any help, here is basically what we are trying, that is working is:

megalodon /SSD/TestData/fast5_pass/ --reference testref.mmi --devices 0 --guppy-server-path /opt/ont/guppy/bin/basecall_server --outputs mod_mappings mods mappings --output-directory /SSD/test_directory/ --processes 30 --remora-model /opt/ont/guppy/data/remora_models_5mc_all_context_sup_r1041_e82.onnx --guppy-config dna_r10.3_450bps_hac.cfg

It seems to be running, but i am not sure if it appropriate, in particular the guppy-config file.

Thanks in advance

**Comment by marcus1487** [comment]
Megalodon is being deprecated. All relevant modified base features from megalodon are or have been ported to Bonito or the production basecallers Guppy/Dorado. I would suggest running bonito for this Rerio all-context model as Guppy does not accept the onnx format model (but bonito with remora under the hood does). I would note that R10.3 is not the same as R10.4.1 and the appropriate model should be matched from bonito and remora. Once in production models (guppy/dorado) this matching will be done for the user.

**Comment by jcolicchio-soundag** [comment]
Thanks Marcus, we are still having trouble with running this in bonito, so i have opened a thread there. But when we try running this with Bonito:

bonito basecaller dna_r10.4.1_e8.2_400bps_sup@v3.5.2 /mnt/NAS2/test/fast5_pass/ --modified-bases 5mC --reference test.mmi > basecalls_with_mods.bam

We get this error: remora.RemoraError: No trained Remora models for dna_r10.4.1_e8.2_260bps. Options: dna_r9.4.1_e8, dna_r9.4.1_e8.1, dna_r10.4_e8.1, dna_r10.4.1_e8.2

**Comment by marcus1487** [comment]
The model is not shipped with Remora as it is only intended for research purposes at the moment. Use the `--modified-base-model` argument to pass the model downloaded from Rerio. use `bonito basecaller -h` to see the help documentation for bonito.

**Comment by jcolicchio-soundag** [comment]
Thanks again!  Gave this a try (--modified-base-model 5mC_all_context_sup_r1041_e82) , but still no luck, receiving the same error.

**Comment by marcus1487** [comment]
You have to point bonito to the actual model file downloaded from Rerio, not just the string name of the model.
