### ISSUE TITLE
model for SQK-LSK109

### ISSUE THREAD

**Issue by zmz1988** [nanoporetech/remora#4]
Dear developers,

Thanks for the nice tool! May I ask you whether I can use the pre-trained model dna_r9.4.1_e8 if my ligation kit is SQK-LSK109 (kit 9?)? If not, do you think it's ok for me to use remora to train my own model? What model or even software for methylation calling do you recommend if my sequencing chemistry is before SQK-LSK110? 

Also, I see that remora only provide models for 5mC. I'm working on plants, and would like to get the information for other types of methylation as well. Could we also use remora to train for other type of modification?

Many thanks!

**Comment by marcus1487** [comment]
Yes. The `dna_r9.4.1_e8` model is the correct one for the kit 9 chemistry (kit 9 and 10 contain the E8 motor; the recently released kit 12 includes the E8.1 motor which requires a new basecalling and remora model).

Yes, the Remora framework can be used to train a model for other modifications and other contexts (currently only CG-contexts released). We are working hard towards releasing models over more modified bases and more contexts.

**Comment by zmz1988** [comment]
Great! Thanks for your reply!
