### ISSUE TITLE
Is remora 5hmC/5mC ready for "prime time"?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/remora#41]
Is the 5hmC/5mC remora mode quantitative enough for biological inference now? Unfortunately I haven't seen any benchmarking papers/preprints out there, and I haven't seen any data on 5hmC performance aside from its introduction in some of the nanopore conferences.

We know that the regular 5mC model is essentially as good/better than bisulfite 5mC calling. Do you have that information for 5hmC/5mC?

**Comment by billytcl** [comment]
Hi! Bumping this. We'd like to use the 5hmC model for a few biological applications but would like to know how interpretable the results would be vs the 5mC only models.

**Comment by marcus1487** [comment]
The released models are certainly very useful, but we did not have concrete ground truths for previous conditions. We have made strides on this front as well as the enzymatic training data and algorithms. Thus the next round of models will have concrete performance metrics and will certainly be ready for "prime time".

**Comment by billytcl** [comment]
Awesome!! Any ETA on when these will be available? Maybe by NCM 22?

**Comment by mp15** [comment]
0a96bfff7419514c3b9d01173b506900c14a3350 looks interesting...
