### ISSUE TITLE
How to draw histogram plots of modified base probabilities using Ml probability tag in modified BAM file?

### ISSUE THREAD

**Issue by kaanokay** [nanoporetech/remora#42]
Hi,

First of all, I'd like to thank you for developing Remora.

I want to compare modified base probabilities between mutant and control groups based on Ml probability tag in modified BAM files that were produced by Remora.

I want to be sure modification difference between two groups is real or not by looking into base probabilities, that's reason why I want to compare probabilities two groups. How to draw a histogram plot based on 5mC probabilities for both groups?

Could you help me with that?

Best.

**Comment by cjw85** [comment]
The probabilities produced by remora are fairly discriminative between modified and not modified, to the point that they can be reliably thresholded to produce a binary decision per-site per-read.

This means one can reliably count reads which are, or are not, modified. The program https://github.com/epi2me-labs/modbam2bed can be used to tabulate such counts.

If you really do wish to tabulate per-site per-read modification probabilities you will likely have to write your own code. Modbam2bed includes a python API that allows you to parse the data by reference position to get all the per-read probabilities for a given site.

**Comment by kaanokay** [comment]
Hi @cjw85,

Thank so much for your quick reply. I think I should use modbampy python package, right?

Bw.
