### ISSUE TITLE
remora model calls different from cell samples and blood samples

### ISSUE THREAD

**Issue by carolinehey** [nanoporetech/remora#43]
Hello
I have sequenced some blood samples and some cell samples recieved from Coriell using the remora modified basecalling models. I Seems to me like more unmodified bases are called from the cell samples. In the picture from IGV the two tracks at the bottom (cells) are far more blue than the three tracks on the top (blood). The same is seen at many other positions. 

![image](https://user-images.githubusercontent.com/98043249/203268830-6bd3abe9-3cb1-4725-876b-525936f8c7e4.png) 

Does anyone have experience with this or seen anything similar?

**Comment by cjw85** [comment]
Hi @carolinehey,

Your question seems prefaced on the fact the observation might not be correct. Can you give more details on the samples and any information on why the results would be expected to be identical, if that is indeed the supposition?

**Comment by carolinehey** [comment]
What information would you like?
I do not expect them to be identical but was just wondering why the cell samples have more positions where no modification is called. If the results are true, why should the blood samples have more methylation than the cell samples? Blood is a mixture of cell types and the methylation pattern was expected to vary more than the uniform LCL.
