### ISSUE TITLE
How to label positive site when I wanna train my own model

### ISSUE THREAD

**Issue by JeremyQuo** [nanoporetech/remora#45]
For example, I wanna train a model to predict methylated A
The previous pipeline seems to label all A in the positive set as positive.
But I just wanna label some of the sites.
How can I do it?

**Comment by marcus1487** [comment]
The `remora dataset prepare` command takes a `--focus-reference-positions` which accepts a bed file with locations at which to extract training chunks with labels specified by the other arguments. See help for any remora command by adding the `-h` or `--help` flag.

**Comment by JeremyQuo** [comment]
The file basecalls.bam can not obtain from bonito, which only supports DNA basecalling.
Thus, is it means that remora 2.0.0 can not support RNA?
So the next question is how to label some of the sites in remora 1.1.1 ?

**Comment by marcus1487** [comment]
Remora has ever provided explicit support for RNA data. The previous version using Taiyaki+Megalodon implicitly supported RNA, but this was not well tested. Part of the reason for breaking the use case with Taiyaki+Megalodon was how hard it was to annotate specific reference positions. As you note this is very tricky with remora <2.0. So currently RNA modified base markup is not supported, but we are working to get Remora support for RNA data integrated back into the Remora software as well as the production basecallers (e.g. Dorado).
