### ISSUE TITLE
How do I use Remora v2 with Guppy?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/remora#46]
How do I use the newest Remora release with Guppy? Or do I have to wait for an integrated release?

I noticed that I could possibly use a separate command that utilizes both the bam and pod5 file, but we are still using fast5s.

**Comment by marcus1487** [comment]
The remora algorithms are integrated into the production basecallers. The Remora software is intended for training models and other advance tasks. We are moving away from support for Guppy and towards supporting Dorado. What task specifically are you looking to perform with Guppy?

**Comment by marcus1487** [comment]
Follow updates for RNA support here: #48

**Comment by billytcl** [comment]
Oh I see. I guess my wording was unclear — I had wanted to use the “v2”
5mC/5hmC models that were released during NCM with Guppy and are ready for
prime time as described in a previous GitHub issue. As far as I know the
latest Guppy was released before that, so is there a way we can take
advantage of the new methylation models plus alignment?

Billy
