### ISSUE TITLE
questions: remora models for R9.4 in guppy, bonito, and dorado

### ISSUE THREAD

**Issue by bakeronit** [nanoporetech/remora#50]
Hi, 

I am using remora models to call methylation with different basecallers, such as guppy v6.1.7, bonito v0.6.2, and dorado v0.1.1.
data is sequenced from Nanopore PromethION with R9.4.1 pore. 

The reason I use multiple callers is that I am confused by those models:
1. keep reading that the guppy is the recommendation since it's already integrated with remora. so I found models like `dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_fast_prom.cfg` and `dna_r9.4.1_450bps_modbases_5mc_cg_fast_prom.cfg` under guppy model folder. Seems like remora can be used to call both 5mc and 5hmc for R9 in guppy? how come I couldn't find them with `remora model list_pretrained`

2. bonito seems will load_model from remora if I don't specify the path of modbase_model and only use `--modified-bases 5mC`.  There is only one available sup model for R9 `dna_r9.4.1_e8_sup@v3.3` in bonito. I am wondering which remora model is eventually used (v3.3, v3.5 or whichever lastest).

3. dorado stores and downloads its own remora models, so for sup mode, currently, there are `dna_r9.4.1_e8_sup@v3.3` and `dna_r9.4.1_e8_sup@v3.4_5mCG@v0`. Since the versions are different. I also need to specify the `--modified-bases-model` separately. 

I think my questions are:

1. Am I using the right remora model in guppy? Is guppy really using remora model to call both 5mC, 5hmC in R9.4.1? how come this is not available in other callers and even remora model list.  and eventually when remora updates the models, do I need to update guppy to get newer models?

2. both bonito and dorado use one `dna_r9.4.1_e8_sup@v3.3` for canonical base calling, should I use latest version of remora modbases models or try to find the matched v3.3. Again, which version of remora is integrated in guppy, bonito, and dorado, respectively? 

Thanks for any comments.

**Comment by marcus1487** [comment]
> Am I using the right remora model in guppy? Is guppy really using remora model to call both 5mC, 5hmC in R9.4.1? how come this is not available in other callers and even remora model list. and eventually when remora updates the models, do I need to update guppy to get newer models?

Yes this is correct. The remora algorithms were re-implemented in Guppy, but the model parameters are the same as those trained and previously released with Remora.

The 5hmC R9 model is available in older versions of Remora (<2.0), but was dropped with the recent Remora update. The R9 5hmC model is significantly worse than the kit14 model, so we would highly recommend that 5hmC analysis going forward be conducted with kit14. The older R9 5hmC model is available in remora <2.0 and Guppy if this is required. We are unlikely to go back and update R9 models at this point as this would detract from moving forward with modified base capabilities in the kit14 system. 

> both bonito and dorado use one dna_r9.4.1_e8_sup@v3.3 for canonical base calling, should I use latest version of remora modbases models or try to find the matched v3.3. Again, which version of remora is integrated in guppy, bonito, and dorado, respectively?

Using the remora model matched to the canonical model will generally give the best results for modified base calling. We aim to keep the modified base models up to date with the canonical models made available.

Bonito runs remora code directly, so the remora version is specified in the bonito dependencies. Guppy and Dorado both independently implemented the production Remora model structure, so there may be some minor implementation differences, but the model parameters are the same in all three cases. Part of the transition from Guppy to Dorado also makes the connection between the remora/bonito/dorado models much closer and unifies the model versioning. 

I hope this helps clear this up a bit, but please do reach out with any further questions.

**Comment by bakeronit** [comment]
Thanks for the replies. 
I am happy to just call 5mC with current data from R9, it seems that I have to upgrade to the latest guppy (6.4) to use Remora> 2.0 models.

note: after my test, bonito and guppy produced pretty similar results (>95% corr with EPIC Array) and bonito is slightly slower. result from dorado + remora (`dna_r9.4.1_e8_sup@v3.4_5mCG@v0`) seems has a better result (>96% corr) and faster (maybe because of without aligning to genome). However, I heard that dorado is still in developing stage, guppy is still the current recommendation in 2023 Q1.
