### ISSUE TITLE
Remora dataset prepare memory scaling on clusters

### ISSUE THREAD

**Issue by mvolar** [nanoporetech/remora#56]
Hello,

I am running remora dataset prepare module on a SGE cluster (I have been able to run the same module on my PC on similar data with no problem, albeit a bit slow).

```
Traceback (most recent call last):
  File "/home/mvolaric/venv-bonito/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/storage/home/mvolaric/venv-bonito/lib/python3.9/site-packages/remora/main.py", line 69, in run
    cmd_func(args)
  File "/storage/home/mvolaric/venv-bonito/lib/python3.9/site-packages/remora/parsers.py", line 275, in run_dataset_prepare
    extract_chunk_dataset(
  File "/storage/home/mvolaric/venv-bonito/lib/python3.9/site-packages/remora/prepare_train_data.py", line 182, in extract_chunk_dataset
    dataset = RemoraDataset.allocate_empty_chunks(
  File "/storage/home/mvolaric/venv-bonito/lib/python3.9/site-packages/remora/data_chunks.py", line 1339, in allocate_empty_chunks
    sig_tensor = np.empty(
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 45.9 GiB for an array with shape (123201525, 1, 100) and data type float32
```

Looks like a memory error. I have asked the cluster for 60G of space. Are there any parameters which I can change to lower the memory requirements.

**Comment by marcus1487** [comment]
Remora datasets are currently very rudimentary and stored completely in memory. We have internal tasks to move this to a dynamic memory solution, but not on the immediate roadmap.

The large memory footprint is due to the number of chunks your run is attempting to produce. Limiting the number of reads (`--num-reads`) or the max reads (`--max-chunks-per-read` default `15`) would be the best bet for this. As a general guideline, our production models use ~60M total training chunks.

**Comment by mvolar** [comment]
I have managed to somehow got it running locally on a large machine with 128GB of RAM, however after running the dataset prepare operation without errors, I got the following on "dataset merge" operation:

```
[11:59:16] Output dataset summary:
               num chunks : 0
       label distribution : Counter()
                base_pred : False
                mod_bases : m
           mod_long_names : ['5mC']
       kmer_context_bases : (4, 4)
            chunk_context : (50, 50)
                   motifs : [('N', 0)]
 chunk_extract_base_start : False
     chunk_extract_offset : 0
          sig_map_refiner : No Remora signal refine/map settings loaded

Killed
```

First 2 times I just got the "Killed" error, afterwards I enabled the "quiet=False" to "quiet=True" in the merge _dataset function to get only this output. What could be the reason for this error?

I have used Bonito for basecalling (without modified base tags) since I plan to train models for both 5mC and 6mA methylation (I have both MsssI and EcoGII treated DNA of interest), and there is no pretrained model for 6mA so the modified base tag for 6mA is out of the question?

I got the following as output for my dataset prepare commands:

Modified:
```
Indexing BAM by read id: 7220745 Reads [12:35, 9561.57 Reads/s]
[15:40:01] Found 7220745 BAM records and 7455607 POD5 reads
[15:40:01] Making reference-anchored training data
[15:40:01] Allocating memory for output tensors
[15:40:01] Processing reads
Extracting chunks: 100%|██████████████████████████████████████████| 7220745/7220745 [1:39:02<00:00, 1215.06 Reads/s][17:19:05] Unsuccessful read/chunk reasons:
1032091 : Chunk sequence too long to store
[17:39:53] Extracted 107279084 chunks from 7220745 reads.
[17:40:02] Label distribution: Counter({1: 107279084})
```

Canonical:
```
Indexing BAM by read id: 8213435 Reads [14:26, 9483.67 Reads/s]
[11:37:49] Found 8213435 BAM records and 9334203 POD5 reads
[11:37:49] Making reference-anchored training data
[11:37:49] Allocating memory for output tensors
[11:37:49] Processing reads
Extracting chunks: 100%|██████████████████████████████████████████| 8213435/8213435 [1:54:00<00:00, 1200.63 Reads/s][13:31:51] Unsuccessful read/chunk reasons:
1269395 : Chunk sequence too long to store
[14:11:36] Extracted 121932130 chunks from 8213435 reads.
[14:11:46] Label distribution: Counter({0: 121932130})
```

**Comment by mvolar** [comment]
It looks like a memory overflow error, once I selection only 3_000_000 reads so the mod_hunks.nz + can_chunks.nz filesizes were ~60% of my RAM the dataset merge worked, and I am now training my first model!

However since I have a fairly powerful machine (i9 + 128GB of RAM) the dataset merge operation is troublesome since I could not get it to merge even 2 50_000_000 chunks (currently at 40mil) files.

**Comment by marcus1487** [comment]
While we are working on solutions for more robust storage for Remora datasets, I would suggest that 80 million chunks is likely more than enough for training. We use 60 million total chunks for training our production models with little to no evidence of overtraining. Is there a reason that you are aiming to use such large training data sizes?

**Comment by mvolar** [comment]
From the documentation and the comments I understood that we need 60mil for both sets not 60mil total. We will see if it fails, it fails.
