### ISSUE TITLE
Correct workflow for preparing mapped .bam files?

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/remora#57]
Greetings,

I'm having difficulties preparing the aligned .bam files for remora's dataset preparation step.
`remora dataset prepare bc1.pod5 bc1_guppy.bam --output-remora-training-file canon.npz --motif CG 0 --mod-base-control`
The .bam was generated using the newest version of guppy as of this post with `--moves_out` as written in the workflow. I get the following error:

> Indexing BAM by read id: 0 Reads [00:00, ? Reads/s]
[14:41:13] Found 0 BAM records and 4000 POD5 reads
[14:41:13] Making reference-anchored training data
[14:41:13] Allocating memory for output tensors
Traceback (most recent call last):
  File "/home/v313/.local/bin/remora", line 8, in <module>
    sys.exit(run())
  File "/home/v313/.local/lib/python3.8/site-packages/remora/main.py", line 69, in run
    cmd_func(args)
  File "/home/v313/.local/lib/python3.8/site-packages/remora/parsers.py", line 275, in run_dataset_prepare
    extract_chunk_dataset(
  File "/home/v313/.local/lib/python3.8/site-packages/remora/prepare_train_data.py", line 196, in extract_chunk_dataset
    assert len(bam_idx.keys()) > 0
AssertionError

I assumed this was because the .bam is unaligned, but after aligning it with guppy_aligner there was no change (perphaps the move tag gets lost?). I generated the unaligned .bam file with dorado `--emit-moves` as well and used `samtools -T '*'` to carry over the move tag to a .fastq file and afterwards aligned it using `minimap2 -y`. However, the error still persists. Am I missing something?

**Comment by marcus1487** [comment]
The most likely culprit here is the `MD` tag in the aligned BAM file. You can add this via the `--MD` tag to minimap2. We will add this to the docs and make the error message more clear in the next release.

**Comment by jorisbalc** [comment]
For some reason even the MD tag didn't help. However, I managed to get the moves table and align using the guppy basecaller only with the following line:

`guppy_basecaller -i canon.pod5 -s  x/ -c dna_r10.4.1_e8.2_400bps_fast.cfg --align_ref ref.fasta --bam_out --moves_out`

This seems to work, but aligning with guppy_aligner doesn't keep the move table. Dorado workaround with samtools and minimap2 did not work for me. Thanks!

**Comment by CWYuan08** [comment]
Dear @jorisbalc, many thanks for your post. 
I tried to copy the command, but my guppy_basecaller couldn't run with just 1 pod file, may I ask how you merged you pod5 files? For the moves table, is it necessary to use the mod config file such as na_r10.4.1_e8.2_400bps_modbases_5mc_cg_hac.cfg? 
Many thanks!

Best regards,
CW

**Comment by jorisbalc** [comment]
Hey,

I think I mistyped the command line in my latest post, `guppy_basecaller` requires a directory with pod5 files. I merged mine before training a model with `pod5 merge `, however it can only merge up to a certain amount of files at once so keep that in mind. The mod config is not needed. I have successfully trained a model using the following workflow:

Basecall your can pod5s: `guppy_basecaller -i can_pod5s/ -s can_calls/ -c dna_r10.4.1_e8.2_400bps_sup.cfg -a ref.fa --bam_out --moves_out --device cuda:0 --num_callers 20`. Do the same for mod pod5s

I merge the output bams with `samtools merge` and follow the provided remora workflow. Hope it helps!

**Comment by CWYuan08** [comment]
Dear @jorisbalc, 

thank you very much! Do we need to run this basecalling twice for both can and mod pod5s? Sorry I am a little confused..I converted all my fast5s to pod5s, thus only one set of pod5s (btw the pod5 package has been upgraded, and now it can merge a large number of files, I just found out!). Do you mean run basecalling with the can cfg and the mod cfg?

Many thanks again!

Best,
CW

**Comment by jorisbalc** [comment]
Yes, the remora model training workflow requires you to have basecalls in .bam format for both the can and mod sequences. I use the same dna_r10.4.1_e8.2_400bps_sup.cfg for both.

**Comment by CWYuan08** [comment]
Dear@jorisbalc,
thank you! Sorry to bother again, maybe I am confused with file formats,  how did you get both can pod5s and mod pod5s? I converted all the raw fast5s directly to pod5s...thus only have one set of pod5s. How to get the two types of pod5s?

Best,
CW

**Comment by jorisbalc** [comment]
I used barcodes to sequence unmodified and modified samples at the same time.

**Comment by CWYuan08** [comment]
Dear @jorisbalc,
thank you! Sorry to bother again, maybe I am confused with file formats, how did you get both can pod5s and mod pod5s? I converted all the raw fast5s directly to pod5s...thus only have one set of pod5s. How to get the two types of pod5s?

Best,
CW

**Comment by CWYuan08** [comment]
Dear @jorisbalc,

I see, sorry I misread the manual. This makes sense!

Thank you very much!

Best,
CW
