### ISSUE TITLE
Possible bug in code

### ISSUE THREAD

**Issue by tcb72** [nanoporetech/remora#58]
https://github.com/nanoporetech/remora/blob/0a96bfff7419514c3b9d01173b506900c14a3350/src/remora/io.py#L320-L335

I was reading through Remora code and I came across this block which I believe contains a bug in line 328. It should read:

`scale_dacs_to_pa=pod5_read_record.calibration.scale`

not 

`scale_dacs_to_pa=pod5_read_record.calibration.offset`

I'm guessing this was caused by a copy/paste + forgetting to change "offset" to "scale". Unsure of what effects, if any, the bug caused.

**Comment by marcus1487** [comment]
This is indeed a bug. This has already been identified internally (during a refactor) and fixed, but thank you very much for the report. This bug is unlikely to negatively effect any results as the pA values are essentially never used in remora. The bug will be fixed in the next release.
