### ISSUE TITLE
training a sequence-specific model

### ISSUE THREAD

**Issue by bobw101** [nanoporetech/remora#6]
Hi Remora Team,

I’m interested in 5-methyl CpG detection on a ~3 kb human sequence that has a very high (~10%) CpG density. Would you recommend training a new model for this specific sequence using a PCR template with and without _in vitro_ M.Sssi methylation?  Would a sequence-specific model have advantages over the currently available pre-trained dna_r9.4.1_e8 model, and what would you recommend for the number of reads to use for training?

Thanks in advance for your advice!

**Comment by marcus1487** [comment]
The currently released models are indeed trained from exactly the samples that you describe. Thus the released models are CG specific. We are working on training all-context 5mC models (hopefully without sacrificing CG-context performance). Look out for updates on that front, but for your purpose the released models should be exactly fit for your purpose.

Note when you run `remora model list_pretrained` the `Remora_Model_Type` column indicates the sequence contexts applicable for each model (currently all `CG`).

**Comment by bobw101** [comment]
Thanks Marcus for clarifying how to use the best models for dense human CpG regions. It's a great tool and we're looking forward to future developments!
