### ISSUE TITLE
Seperating fast5 format files?

### ISSUE THREAD

**Issue by ronald-j** [nanoporetech/remora#60]
as i understand remora takes in pod5 files now, but before converting my fast5s into pod5s is there a way to seperate them by barcode? or for this specific remora workflow you have to sequence using only the sample of interest?

**Comment by marcus1487** [comment]
I would suggest that you use the pod5 tools to perform this task. Namely the pod5 subset command should suffice for this task. We can also look into adding a read ids option to the ``remora dataset prepare`` function to avoid this extra file creation.
