### ISSUE TITLE
Train on any context for 6mA and 5mC at the same time

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/remora#63]
Hi remora creator,
Is there any sample requirement for train models for any context motif option (N 0)? Like how many reads will be enough for this training?
Another thing is can I do something like this when train: "--mod-base m,a 5mC,6mA --motif N 0", if I have the right positive and negative data?
Thanks,
Yijun

**Comment by Bessem06** [comment]
Dear Yijun,

Have you found a way to train the models? If so, can you share your pipeline?

Thank you
Bessem

**Comment by marcus1487** [comment]
This is a large area of research internally, but at a high level I would suggest that 100% spike-in samples are not likely to be a robust training sample for identifying modified bases in isolation. The 100% spike-in sample will change the entire signal spectrum (expected k-mer levels even for those k-mers not including any A or C bases). This causes a number of issues.

I would suggest that training samples should be as close as possible to the target molecule as is reasonably possible. I understand that this is a tall task for modified bases where a per-read per-site ground truth is often difficult to obtain. We are hard at work to produce a solution using "randomers" (printed oligos with modified bases is a fixed position surrounded by random bases), but this data prep and analysis pipeline is not yet publicly available.

**Comment by Yijun-Tian** [comment]
Thanks for the insight, @marcus1487. Lucky to know 100% won't do good for the training processes.  
BTW, if I plan to detect two modifications from one sample, do you like Plan A: prepare two modifications in one sample (this sample can list signals for adjacent mA and mC in real reads), and do training model and infer separately, or Plan B: prepare two positive samples with stand alone modification. Does Plan A sounds better?

**Comment by marcus1487** [comment]
Remora model are intended to be unique for each distinct canonical base. So for example, 5mC and 6mA would be separate models, but 5mC and 5hmC are contained in one model as they are alternatives to the same canonical base. At inference time (for example within Dorado) the models will be applied at the same time and output into the resulting BAM file, so the separation of the models is not directly seen at inference time.

That being said, if you would like to detect two modified bases in close proximity this will effect the nanopore signal/current. So supplying the model with training examples with multiple modified bases during training would likely produce a more robust model. Producing training samples with this type of data may prove cumbersome, but hopefully this insight will be helpful in producing useful training data.
