### ISSUE TITLE
user friendly guide

### ISSUE THREAD

**Issue by Bessem06** [nanoporetech/remora#64]
Hi,

I am trying to look at methylations (5mC, 5hmC and 6mA) for my bacteria. I tried using Megalodon, but there are some connection problems. Since Remora is the new program to use, I am trying to look for tutorials, but nothing seems to be available. 
Are there some documents with a detailed list of the different options? Is there a user-friendly guide or a tutorial for starting with this kind of analysis for beginners?

Thank your
Bessem

PS: I am not trying to build a new model but use the "res_dna_r941_min_modbases-all-context_v001" model from rerio on my data.
PPS: My starting data are a genome and one set of fast5 files

**Comment by marcus1487** [comment]
Hi @Bessem06 , This repository is primarily intended for the advanced user of modified bases in nanopore data. The algorithms underpinning this repository are used in the modified base detection within the production solutions (Guppy and transitioning to Dorado). Thus I would suggest running Dorado using the models shipped with Dorado for modified base calling.

For the "res_dna_r941_min_modbases-all-context_v001" model, this model is based on the previous version of modified base calling (integrated into the canonical basecaller). Thus this is not a Remora model and not ported forward into Dorado or current production solutions. We are hard at work to get a Remora all-context model and hope to have this released in the near future. Note that the next all-context model release is targeted for kit14 data and is not like likely to target R9 series data in the near future.

**Comment by marcus1487** [comment]
For detection of modified bases in all-contexts the current R9 Rerio model (runnable with Guppy) is the current research offering. We are working hard towards much improved all-context 5mC and 6mA models.
