### ISSUE TITLE
"invalid syntax" when running model train

### ISSUE THREAD

**Issue by kewei2019** [nanoporetech/remora#65]
Hi,
I'm recently using remora to find methylations for my bacteria and yeast data. It seems fine when ran the data preparation and merge, but something went wrong when running model train. Here I attached the commands:
1. data preparation:
![image](https://user-images.githubusercontent.com/52051945/230154293-33868bc5-2280-4b99-8e98-c1008fe5d453.png)
![image](https://user-images.githubusercontent.com/52051945/230154452-675eeac6-1bc6-4078-abcf-8ae788beaaac.png)

2. merge:
![image](https://user-images.githubusercontent.com/52051945/230154591-4e173940-191b-4d16-9874-0333a60c5b4c.png)

3.  model training:
![image](https://user-images.githubusercontent.com/52051945/230154786-5e91d6bf-8d1c-4ecc-9dc6-1bc8e69599cb.png)

Not sure how to deal with this. Thank you for your help!
And another question: I also want to find 6mA in "GATC" motif, what commands I should use? Seems like there is no tutorial for this.
Thank you so much!

**Comment by kewei2019** [comment]
@marcus1487 
Hi, Marcus! Thank you for the suggestions! I still have several questions.
1. I tried to use modkit motif-bed, it requires fasta, motif and offset. Not sure what fasta I should put in. The only file that worked was genome.fasta, but it didn't show any single letter code. I will move some related questions to modkit page later.
command: modkit motif-bed E.coli_k-12_genome.fasta GATC 1
output looks like:
![image](https://user-images.githubusercontent.com/52051945/233722407-e9306310-d091-4994-92e2-b4da20074940.png)

2. When running remora infer on a large data, CPU and memory were occupied by 60% and 88% respectively. And soon remora stop automatically. How to deal with this problem?
![image](https://user-images.githubusercontent.com/52051945/233724677-d410fe2c-06db-4698-ad16-6a93d39810f8.png)

3. 'remora dataset prepare' has a option --motif, if I want to call 5mC or 5hmC, it should be '--motif CG 0'. So, for calling 6mA in 'GATC' motif, should I type in '--motif GATC 1'? Am I understand correctly?

Thanks!
Kewei Xu

**Comment by marcus1487** [comment]
The motif bed command produces a BED file with the locations. If you would like to annotate those locations with a modified base code that should be done downstream of modkit. There are no scripts for this, but could be carried out with an awk one-liner, for example `awk 'BEGIN{OFS="\t"} {$4="m"; print}' motifs.bed > motifs_w_mod.bed`.

v2.1 should address the second point here.

For issue 3, yes `--motif GACT 1` is the correct syntax here.
