### ISSUE TITLE
Question: base modification detection for direct RNA sequencing data

### ISSUE THREAD

**Issue by yzhang-github-pub** [nanoporetech/remora#70]
Dear Authors,

The names of all currently available pre-trained models start with 'dna'. Can them be used for RNA sequencing data for m6A and m5C? Please advise.

**Comment by marcus1487** [comment]
DNA models are not applicable to RNA data. There are currently no released RNA Remora models. We are working towards this goal. The latest release of Remora added support for researchers to explore, train and assess RNA data, but no RNA models are currently available.
