### ISSUE TITLE
Annotation of data

### ISSUE THREAD

**Issue by kewei2019** [nanoporetech/remora#71]
Hi,
I have successfully used Remora to analyze my trained bacteria genome for m6A in GATC sites. However, I am unsure about the meaning of each lane in the output and how to determine whether a site is methylated or not.

And correct me if wrong:
query_name: reads' name
ref_name: chromosome name
ref_pos: position on chromosome

Thanks very much!
Kewei
![image](https://github.com/nanoporetech/remora/assets/52051945/84ced51c-c536-43a7-8d78-ee86957b0339)

**Comment by marcus1487** [comment]
Here is a brief description of each column in this output.

- query name: read identifier/name
- query position: position within the read basecalls
- ref_name: chromosome/contig name from FASTA
- ref_pos: position within reference record
- strand: reference mapping strand
- gt_mod_idx: The index within the labels of the ground truth (gt) modified base. `0` is canonical. Other indices follow from the labels called by the model. For a 6mA-only model the only other value would be `1` indicating a ground truth modified position
- mod_probs: Probability of each label output by the model at this position
- ref_align: section of reference/chromosome alignment in direct proximity of the call
- query_align: section of query/read alignment in direct proximity of the call
- within_align: Is this position within the mapped portion of the read
- within_gt: Is this position on the reference between the first and last labeled base on the reference (mostly applicable for printed oligonucleotides)

**Comment by kewei2019** [comment]
Hi, more quick questions:
1. For the mod_probs, actually it contains two floats, like: "0.341796875,0.658203125" and "0.990234375,0.009765625". So which float represent the probability at one position?

2. For the gt_mod_idx, you said "0 is canonical, 1 is ground truth modified position", but I found a lot of positions that are "none", what does ''none" mean?
![image](https://github.com/nanoporetech/remora/assets/52051945/410a582d-f4ce-422a-aefe-95a03407641e)
![image](https://github.com/nanoporetech/remora/assets/52051945/77163aac-f27e-44ce-8e89-a3a27a88e3e1)
