### ISSUE TITLE
assign motif with degenerate code

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/remora#74]
Hi @marcus1487 ,
Is it possible to use degenerate code when prepare dataset? e.g. --motif [AGT]A[AGT] 1 as --motif DAD 1？In my training, I found adding an additional base in the motif increases the acc_train and acc_val a lot.
Thanks,

**Comment by marcus1487** [comment]
Yes. Prepare dataset does take degenerate IUPAC codes. So `--motif DAD 1` will indeed work for prepare dataset. Note that this means that the trained model will only make calls in the `DAD` motif though. We are working on making the dataset preparation/model motif applications a bit more robust, so please reach out if you'd like some pointers for specific applications.
