### ISSUE TITLE
Problem of data prepare on version 2.1.1 

### ISSUE THREAD

**Issue by JeremyQuo** [nanoporetech/remora#76]
I tried to run remora train after update today.

I get my bam file by add parameter `--moves_out --bam_out` in guppy.
And cat it by samtools merge returns lack of MD tag
Then I run 
`samtools fastq pass.bam | minimap2 -ax map-ont --MD refernce.fa -t 8 --secondary=no -|samtools view -hbS -F 260 -|samtools sort -@ 6 - -o sort.bam`

After get new bam I start to run remora.
when I run 
`remora dataset prepare  xxx.pod5  sort.bam --output-remora-training-file can_chunks.npz --log-filename prep_can.log     --refine-rough-rescale --motif A 0 --mod-base-control --refine-kmer-level-table levels.txt`
what is level.txt file? I don't know if it is available on my data.
And it returns
`Indexing BAM by read id: 2354 Reads [00:00, 148776.32 Reads/s]
[13:54:32] Extracting read IDs from POD5
[13:54:32] Found 2354 BAM records, 2426 POD5 reads, and 2354 in common
[13:54:32] Making reference-anchored training data
[13:54:32] Allocating memory for output tensors
[13:54:32] Processing reads
Extracting chunks:   0%|                           | 0/2354 [00:03<?, ? Reads/s]
[13:54:36] Extracted 0 chunks from 2354 reads.
[13:54:36] Label distribution: Counter()`

My question is 
1. Do I use the correct method to generate the special bam remora requires?
2. What is level.txt file? I don't know if it is available on my data.
3. Why does it extract  0 chunks?

Many thanks for your help if possible.

**Comment by marcus1487** [comment]
Level tables can be found in the kmer_models repository here: https://github.com/nanoporetech/kmer_models

For the data processing, my best guess is that you have dropped the move tags from the bam with the `samtools fastq` step. You can add the `-T "*"` option to copy the tags in the fastq conversion step and then the `-y` option to copy the tags in the minimap2 step. Alternatively dorado 0.3.0 has added reference mapping which will handle all of this for you and is the new recommendation. This should resolve the 0 chunks issue.

I would also recommend that you specify the log output option to remora commands as the log generally has the information for the issues with data generation.
