### ISSUE TITLE
inference enhancement when using GPU

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/remora#79]
Hi,
Is there a way or can some options be changed to take full advantage of our GPU when using remora to infer? Seems the utility is low and the speed is slow

```
remora infer from_pod5_and_bam GM12878_SMACseq.pod5 GM12878_SMACseq.bam --model train_${i}/model_best.pt --out-bam GM12878_SMACseq_infer.${i}.bam --device 0
******************** WARNING [20:53:00:MainProcess:MainThread:refine_signal_map.py:258]: K-mer table provided, but not used. See rough rescaling options. ********************
Indexing BAM by read id: 1701230 Reads [04:25, 6417.70 Reads/s]
[20:57:26] Extracting read IDs from POD5
[20:57:27] Found 1352277 BAM records, 1575504 POD5 reads, and 1352277 in common
Inferring mods:  27%|████████████████████▍                                                        | 359783/1352277 [14:08:44<39:01:19,  7.07 Reads/s, 0.54 Msamps/s]
```

```
$ nvidia-smi
Tue May 23 11:15:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    Off  | 00000000:73:00.0 Off |                  Off |
| 34%   63C    P2    85W / 300W |   4568MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1892      C   ...bin/guppy_basecall_server     2698MiB |
|    0   N/A  N/A      3316      G   /usr/lib/xorg/Xorg                 64MiB |
|    0   N/A  N/A      3435      G   /usr/bin/gnome-shell                7MiB |
|    0   N/A  N/A    981868      C   ...remora/venv/bin/python3.8     1794MiB |
+-----------------------------------------------------------------------------+
```

**Comment by marcus1487** [comment]
We are looking into this internally. This requires a bit of a refactor to batch the reads to make better use of the GPU resources. Depending on your target producing the Remora dataset and inferring from this can be significantly faster. That though that certain information is lost in this process and one should be careful about whether they are testing on reference or basecall anchored remora settings.

I would recommend that the production runs should not depend on remora as this is a research repository and not intended for high end performance. I would recommend Dorado where performance is a priority.

**Comment by marcus1487** [comment]
This is bit of a higher level question. If you have a very high modified base content (>10% of a single base) then the lower quality scores may be due to the modified bases. The ultimate answer is that you'd like to present the same data type at training time where you'd expect the model to perform well at inference/application time. So if you'd like to call the "fail" type reads, then they should be included in training. If you prefer a model to optimally only call the pass reads, then only include pass reads in trianing.

**Comment by Yijun-Tian** [comment]
I see. I'll give the failed reads a training test to see if the new model will infer better for the heavily modified reads. The reads may fail when used for training; as long as they are mapped somewhere, they can still provide information. Thanks for the insight!
