### ISSUE TITLE
Remora model selection with different accuracy

### ISSUE THREAD

**Issue by ingniy** [nanoporetech/remora#8]
Hi developers,

Thanks for this nice tool. We are using Remora model with guppy config file (dna_r9.4.1_450bps_fast/hac/sup.cfg) accordingly for 5hmC calling for the same sample, but the proportion results show some difference, especially for super accuracy one as below,

dna_r9.4.1_e8 fast 0.0.0 5hmc_5mc CG 0 -- 0.07761384709206084
dna_r9.4.1_e8 hac 0.0.0 5hmc_5mc CG 0 -- 0.07974461372838691 
dna_r9.4.1_e8 sup 0.0.0 5hmc_5mc CG 0 -- 0.19680854712480966

Would you please provide some suggestions on Remora model selection for 5hmC and 5mC calling of human DNA samples?

Thank you very much.

Best regards,
Ying

**Comment by marcus1487** [comment]
Could you provide a bit more detail on how the "proportion results" were derived and what they represent?

In general the super accuracy models are recommended for the highest accuracy.

**Comment by ingniy** [comment]
The proportion was calculated using the sum product of methylated C ratio and coverage divided by the sum coverage generated from modified_bases.bed, like ([10]/100*[9]).sum()/[9].sum(), which considered as methylation level at overall position.
[9] and [10] represent the last two columns of modified_bases.bed as megalodon output.
