### ISSUE TITLE
Error when running remora infer duplex_from_pod5_and_bam in GPU 

### ISSUE THREAD

**Issue by santanaw** [nanoporetech/remora#83]
Hi @marcus1487, thanks for developing remora. I am experiencing a similar problem as that found in #67 when `running remora from_pod5_and_bam.` In my case, I am running  `remora duplex_from_pod5_and_bam` with my R10 data using the models provided in the current **remora v.2.1.1 release** `dna_r10.4.1_e8.2_4khz_400bps_sup_v4.1.0_5hmc_5mc_CG_v2.pt`. If I run my command in the **CPU** (i.e. without `--device 0`) the job is completed -only with multiple warnings, as I don't provide mapped reads in the bam files.

```
remora infer duplex_from_pod5_and_bam \
merge.pod5 \
simplex.movetab.bam \
duplex.bam \
duplex_pair_ids.txt \
--model ${REMORA_DIR}/dna_r10.4.1_e8.2_4khz_400bps_sup_v4.1.0_5hmc_5mc_CG_v2.pt \
--out-bam duplex.mod.bam \
--log-filename duplex.mod.log 
```
Output:
```
DEBUG [01:29:35:BuildDuplexedIoReads_0:MainThread:io.py:1529] Reference sequence requested, but could not be extracted. Do reads contain MD tags?
DEBUG [01:29:36:BuildDuplexedIoReads_0:MainThread:io.py:1529] Reference sequence requested, but could not be extracted. Do reads contain MD tags?
```

However, this is not the case when running the tool in the **GPU** ( i.e. `--device 0` in an A100) with mapped or unmapped input data.  The output bam file is empty and it throws the same Traceback errors in regards to Torchscript as shown in #67. Also reproduced the error using the test data in this repository.

```
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: shape '[2, 0, 1]' is invalid for input of size 1099776
'.
Full traceback: Traceback (most recent call last):
  File "/software/envs/remora_v2.1.1/lib/python3.8/site-packages/remora/util.py", line 413, in _mt_func
    out_q.put(func(val, *args, **kwargs))
  File "/software/envs/remora_v2.1.1/lib/python3.8/site-packages/remora/inference.py", line 545, in add_mod_mappings_to_alignment
    mod_tags = caller.call_duplex_read_mods(duplex_read)
  File "/software/envs/remora_v2.1.1/lib/python3.8/site-packages/remora/inference.py", line 163, in call_duplex_read_mods
    duplex_read_probs = self.call_duplex_read_mod_probs(duplex_read)
  File "/software/envs/remora_v2.1.1/lib/python3.8/site-packages/remora/inference.py", line 114, in call_duplex_read_mod_probs
    template_probs, _, template_positions = call_read_mods(
  File "/software/envs/remora_v2.1.1/lib/python3.8/site-packages/remora/inference.py", line 82, in call_read_mods
    nn_out, labels, pos = read.run_model(model)
  File "/software/envs/remora_v2.1.1/lib/python3.8/site-packages/remora/data_chunks.py", line 513, in run_model
    output = model(sigs, enc_kmers).detach().cpu().numpy()
  File "/software/envs/remora_v2.1.1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: shape '[2, 0, 1]' is invalid for input of size 1099776
```
Following the advice on #67 regarding the torch versions, I was able to ran my job using the torch model file from the current remora release using remora v2.0.0 (which comes with torch < 2.0.0). Please note that for all remora versions, I have installed them with pip in a virtual environment. 

Questions:
1. Is there any chance the model `dna_r10.4.1_e8.2_4khz_400bps_sup_v4.1.0_5hmc_5mc_CG_v2.pt` of the current release is not compatible with torch >= 2.0.0? If so, could we get a model compatible with the current torch version in remora so the GPU feature could be used?
2. Is it possible to use the previously mentioned model to call modifications in simplex reads ( i.e. `from_pod5_and_bam`) ? Might the inferences be the same compared to Dorado modification calls (of course using the matching model) ?
3. Is it fine/any reason to get the next warning when launching my previously mentioned processes?  `**WARNING [22:21:06:MainProcess:MainThread:model_util.py:253]: reverse signal attribute not found in model. Assuming False**` 

Thank you for any information.

**Comment by marcus1487** [comment]
We will work on getting this model updated to be compatible with the latest torch release.

Yes the same model applied in a simplex fashion from either Dorado or `remora infer from_pod5_and_bam` should produce the same modification calls as Dorado (down to implementation details). 

Yes This warning is fine. RNA support added a new attribute to the models. Older models are all DNA (not 3' to 5' signal) and so these warnings are not a problem and just alerting to backwards compatibility checks.

**Comment by santanaw** [comment]
Thank you for the clear and prompt responses.

**Comment by marcus1487** [comment]
The latest update (version 2.1.2) should resolve this issue. Please re-open this issue if you experience further issues.

**Comment by santanaw** [comment]
Thank you @marcus1487. I could test the model of the version 2.1.2 using GPU and the process runs really well. Thanks again.
