### ISSUE TITLE
Difference about rescale between tombo and remora

### ISSUE THREAD

**Issue by JeremyQuo** [nanoporetech/remora#84]
Tombo said it used thei_sen algorithm after v1.3 and Remora now uses rescale or rough_rescale.
Is any difference between these two normalization algorithms?
Which one will be better to help me show the site of modified sites on RNA and why.
I am really confused by the rescaling method.
Can you explain more details about it, please?
Many thanks

**Comment by marcus1487** [comment]
There are two sets to the rescaling algorithms in Remora/Tombo (before and after precise signal to sequence alignment, aka re-squiggling). 

The first set of rescaling algorithms start from the rough alignment between the signal and basecalls which comes from the basecaller. These signal assignments are not ideal for any signal based metric analysis, but are sufficient for the Remora models to predict modified bases (without the extra compute cost for refining the signal to basecalls boundaries). 

The second set of rescaling algorithms concern the rescaling after the precise signal to sequence alignment. For these methods the signal based metrics (e.g. mean current at each base) are now meaningful and should correspond to the expected levels given the sequence.

In Tombo the first stage of re-scaling only performed simple median and MAD scaling (take the median and MAD of the entire signal block). In Remora a new rough rescaling was added here. This method takes only a single value from each estimated base from the basecaller and compares the quantiles of these values to the quantiles of the expected levels from the kmer model for the produced sequence. This procedure produces much more robust scaling values without the compute cost of precise signal assignment.

The Theil-Sen re-scaling is applied in the second stage after re-squiggling. This method has not been ported over to Remora, but we will look into adding this option for research models. The method in Remora is a simple least squares estimate of the correct scaling factors. Note that no production Remora models perform precise signal refinement so this is not relevant to any production models.

**Comment by JeremyQuo** [comment]
Many thanks！
