### ISSUE TITLE
remora RNA mod test failed

### ISSUE THREAD

**Issue by vetmohit89** [nanoporetech/remora#85]
Hello, I used test dataset and using following sbatch file:  

#!/bin/bash
#SBATCH -J remora.job
#SBATCH -o remora.%j.out
#SBATCH -e remora.%j.err
#SBATCH -p short
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=5G
#SBATCH --cpus-per-task=48

module load Anaconda3/2022.05
conda activate remora

remora \
  analyze plot ref_region \
  --pod5-and-bam can_reads.pod5 can_mappings.bam \
  --pod5-and-bam mod_reads.pod5 mod_mappings.bam \
  --ref-regions ref_regions.bed \
  --highlight-ranges mod_gt.bed \
  --refine-kmer-level-table levels.txt \
  --refine-rough-rescale \
  --log-filename log.txt

It is giving following error:
Traceback (most recent call last):
  File "/home/mbansal/.local/bin/remora", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/mbansal/.local/lib/python3.11/site-packages/remora/main.py", line 71, in run
    cmd_func(args)
  File "/home/mbansal/.local/lib/python3.11/site-packages/remora/parsers.py", line 1566, in run_plot_ref_region
    from remora import log, io, refine_signal_map
  File "/home/mbansal/.local/lib/python3.11/site-packages/remora/io.py", line 23, in <module>
    from remora import log, util, data_chunks as DC, duplex_utils as DU, RemoraError
  File "/home/mbansal/.local/lib/python3.11/site-packages/remora/data_chunks.py", line 11, in <module>
    from remora.refine_signal_map import SigMapRefiner
  File "/home/mbansal/.local/lib/python3.11/site-packages/remora/refine_signal_map.py", line 102, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/mbansal/.conda/envs/remora/lib/python3.11/dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/mbansal/.conda/envs/remora/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbansal/.conda/envs/remora/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbansal/.conda/envs/remora/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'numpy.ndarray'> for field sd_arr is not allowed: use default_factory

**Comment by marcus1487** [comment]
This should have been fixed in the latest patch release. Are you using the latest version (we don't support conda distribution, so may require a pip install)? Latest version is 2.1.2.

**Comment by vetmohit89** [comment]
Hello Marcus,

Thank you so much. I will try new version. But please let me know how we can generate mod_gt.bed and can_gt.bed..

**Comment by marcus1487** [comment]
The `gt` stands for ground truth. These files contain the ground truth modified or canonical base locations in the bioinformatics standard BED format. For the purposes of this plotting function they are provided simply to highlight positions of interest. In other commands they may provide more functional purposes.

**Comment by vetmohit89** [comment]
Do I have to use these gt files for my bam files analysis? These gt (ground truth) files have only Chr 13 data. If not, how can I generate these files for my data analysis? Or do I need these files for my sample analysis?

**Comment by marcus1487** [comment]
What is the goal of your analysis? Please provide a detailed description of your samples and the target metrics you are aiming to produce. This will lead the answer to the question about the requirements and how you would go about producing the relevant files required.

**Comment by vetmohit89** [comment]
Dear Marcus,

I have control and knockdown samples bam file and a list of potential sites where modification is present in control samples. Now, I want to see resquiggle data for the same modifications using current.

**Comment by vetmohit89** [comment]
Hello Marcus,

Here are the steps I followed but it is giving error remora.RemoraError: BAM record not found in POD5

1. Converted all fast5 to pod5 using pod5 tool
2. Used guppy basecaller to get unaligned bam files with move tables with following command
guppy_basecaller \
-i fast5 \
-s pass \
-c rna_r9.4.1_70bps_hac.cfg \
--reverse_sequence \
--bam_out \
--moves_out \
--compress_fastq \
-x "cuda:all" --num_callers 5 --gpu_runners_per_device 8 \
--chunks_per_runner 100 --chunk_size 100

3. Used guppy aligner to generate mapped bam files: guppy_aligner -i bam/ -s / --align_ref GRCh38.p13.genome.fa --align_type auto --bam_out --index
4. Merged all bam files using samtools merge xxxx.bam bam*.bam
5. Index merged bam files
6. merged pod5 files using pod5 merge *.pod5 -o merged.pod5
7. At last: remora analyze plot ref_region --pod5-and-bam merged/merged.pod5 merg
ed_BE2C_PUS7.bam --ref-regions ref_regions.bed --refine-kmer-level-table levels.txt --refine-rough-rescale --log-filename log.txt but it is giving error RemoraError: BAM record not found in POD5
I think i missed metadat file. I could not generate it. Please help!

**Comment by vetmohit89** [comment]
Hello, 

Instead of using guppy aligner for generating bam mapped files. I used guppy basecaller command to generate mapped bam files. Here are the commands: guppy_basecaller \
-i /fast5 \
-s /fast5 \
-c rna_r9.4.1_70bps_hac.cfg \
--reverse_sequence \
--align_ref GRCh38.p13.genome.fa  \
--align_type full \
--bam_out \
--moves_out \
--compress_fastq \
-x "cuda:all" --num_callers 5 --gpu_runners_per_device 8 \
--chunks_per_runner 100 --chunk_size 100

I merged all the bam files using samtools command followed by sort and index. I used these sorted bam and merged pod5 files for using remora and it works fine.
