### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by ragak** [nanoporetech/remora#86]
Hi, I am running megalodon with remora models, and the program is searching for the following model, which it does not find: dna_r10.4.1_e8.2_400bps_fast_v4.2.0_5hmc_5mc_CG_v2.pt. I have downloaded the latest models using 'remora model download', and the above model is not one of them. I do see dna_r10.4.1_e8.2_5khz_400bps_fast_v4.2.0_5hmc_5mc_CG_v2.pt, is that the same model? Can they be used interchangeably? Thank you!

**Comment by marcus1487** [comment]
Megalodon is deprecated and I would not recommend using it as it is not under active development. How did you arrive at the `dna_r10.4.1_e8.2_400bps_fast_v4.2.0_5hmc_5mc_CG_v2.pt` file? I don't believe this model has been produced. The v4.2.0 models are exclusively for 5kHz data type so if that is the data that you have then this would be the correct model. If you have 4 kHz data then I would recommend the <v4.2 models. Automatic model selection is also somewhat fragile in the research repositories. I would recommend Dorado for any analysis running standard modified base calling.

**Comment by ragak** [comment]
Thank you for the quick response. I received an error message calling out that file. But I will switch to Dorado as you suggest, thanks again.
