### ISSUE TITLE
Remora R9.4.1 5mC+5hmC benchmarks

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/remora#87]
It would be nice to have some benchmark stats for R9.4.1 5mC+5hmC modified basecalls. Does one exist? Also for R10?

**Comment by marcus1487** [comment]
From my NCM 2021 presentation there are benchmark figures for R9 data. We did not have ground truth validation strands at this time so these benchmarks are not ideal, but show the general utility of the model.

<img width="1032" alt="image" src="https://github.com/nanoporetech/remora/assets/13755444/a4015b3d-39c1-4227-8fff-fa81d0c7c6b7">
<img width="1063" alt="image" src="https://github.com/nanoporetech/remora/assets/13755444/7534261a-66a4-43e9-bfce-f1f6305f6994">

For kit14 the most recent benchmark numbers were presented at London Calling. These were from synthetic ground truth strands and thus represent our best estimation of the per-read per-site accuracy (single read single, site accuracy without aggregation). Note that these metrics apply a filter of the 10% least confident calls which is the default in the `modkit pileup` command. Also note that this filter makes no use of the ground truth sample and so is applicable to any sample. Any pileup benchmarks can be derived from these per-read per-site statistics.

<img width="462" alt="image" src="https://github.com/nanoporetech/remora/assets/13755444/b761e423-f798-41b9-b870-09bdd31b48fe">

**Comment by billytcl** [comment]
Thanks!! Is there a white paper or something on Nanopore's website that I could use as a citation? This is something that would be really helpful for grant applications and manuscripts -- common question that comes up.

**Comment by marcus1487** [comment]
We do not have any citation for these benchmarks of which I am aware. You might have some luck reaching out to support on this one.
