### ISSUE TITLE
m5c interference 

### ISSUE THREAD

**Issue by gaoxiangcao** [nanoporetech/remora#89]
If I only want to inference m5c sites inference, can I only use the pre-trained model or could you give me some advices on running on cpu mode?

**Comment by marcus1487** [comment]
I am not sure I understand your request. Could you add some detail on what you desire? What you have attempted? And what issues you've encountered in these attempts?

**Comment by gaoxiangcao** [comment]
Hi，I'm sorry for not expressing my needs clearly. I  want to use remora to predict m5c sites from raw data，does it work in a CPU only mode？because i don‘t have a server with GPU. if it works with CPU mode，could you give me some advice on the command of running？

**Comment by gaoxiangcao** [comment]
or Could you give me a detailed description of how to process RNA m5C modification data step by step

**Comment by marcus1487** [comment]
Remora is the research interface for the purpose of training modified base models and investigating signal towards this goal. The recommended interface for inference on production Remora modified base models is Dorado. 

At the moment we do not have any RNA modified base models released. The Remora commands are compatible with RNA data should users desire to train their own RNA modified base models though.

I hope this helps and do let me know if you have any further questions.
