### ISSUE TITLE
Which model to use for 5hmC calling

### ISSUE THREAD

**Issue by e-sollier** [nanoporetech/remora#9]
Hello,

I would like to use bonito/remora to call hydroxymethylation. While the 5mC calling seems to work fine, I get the following error when I try to run `bonito basecaller dna_r9.4.1_e8_sup@v3.3 fast5/ --modified-bases 5hmC --reference reference.mmi > basecalls_with_5hmC.bam`:

```
> loading model dna_r9.4.1_e8_sup@v3.3
> loading modified base model
> warning (remora): Remora model for basecall model version (v3.3) not found. Using default Remora model for dna_r9.4.1_e8_sup.
--- Logging error ---
Traceback (most recent call last):
  File "/miniconda3/envs/bonito/lib/python3.7/site-packages/remora/model_util.py", line 452, in load_model
    submodels = submodels[modified_bases]
KeyError: '5hmc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/envs/bonito/lib/python3.7/logging/__init__.py", line 983, in emit
    msg = self.format(record)
  File "/miniconda3/envs/bonito/lib/python3.7/logging/__init__.py", line 829, in format
    return fmt.format(record)
  File "/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/mod_util.py", line 25, in format
    self._style._fmt = self.fmt
AttributeError: 'CustomFormatter' object has no attribute 'fmt'
Call stack:
  File "/miniconda3/envs/bonito/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/cli/basecaller.py", line 59, in main
    args.modified_bases, args.model_directory, args.modified_base_model
  File "/miniconda3/envs/bonito/lib/python3.7/site-packages/bonito/mod_util.py", line 52, in load_mods_model
    quiet=True,
  File "/miniconda3/envs/bonito/lib/python3.7/site-packages/remora/model_util.py", line 455, in load_model
    f"Remora model for modified bases {modified_bases} not found "
Message: 'Remora model for modified bases 5hmc not found for dna_r9.4.1_e8_sup@0.0.0.'
Arguments: ()
```
When I run `remora model list_pretrained`, the pore dna_r9.4.1_e8 does appear to have a model available for 5hmc:
```
Pore             Basecall_Model_Type    Basecall_Model_Version    Modified_Bases    Remora_Model_Type      Remora_Model_Version
---------------  ---------------------  ------------------------  ----------------  -------------------  ----------------------
dna_r9.4.1_e8    fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8    hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8    sup                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8    sup                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8.1  fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1  hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1  sup                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   fast                   0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1   hac                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r10.4_e8.1   sup                    0.0.0                     5mc               CG                                        0
dna_r10.4_e8.1   sup                    0.0.0                     5hmc_5mc          CG                                        0
```
Thanks in advance for your help.

**Comment by marcus1487** [comment]
A standalone model for 5hmC has not yet been released. To get 5hmC calls I would recommend using the appropriate `5hmc_5mc` model. This can be specified in Bonito with the `--modified-bases 5mC 5hmC` option. 

Is there a specific use case where you would like 5hmC calls without 5mC calls? In my experience most biological samples with 5hmC contain 5mC as well, while several use cases exist for 5mC calling alone.

One point that may help here is that when calling modified bases, all alternatives to a canonical base should be considered at once. That is to say that running a 5mC-only model and a 5hmC-only model does not produce the same results as a 5mC+5hmC model. The release of the 5mC-only model was intended to give higher accuracy results which is applicable for more users. 

If there are specific use cases in which you are interested that information would be greatly useful for setting our internal focus.

**Comment by e-sollier** [comment]
Thanks a lot for your answer !
I do in fact want to call both 5mC and 5hmC. The only reason why I tried to call 5hmC separately was that I wanted to make sure that I interpreted the ML tag in the output bam file correctly. If I understand correctly the [SAM tags](https://samtools.github.io/hts-specs/SAMtags.pdf) the first values correspond to 5hmC likelihoods and the following ones to 5mC, since C+h comes before C+m in the MM tag, and I thought I could check this by calling 5mC and 5hmC separately. But it makes sense that a 5mC+5hmC model cannot call 5hmC independently !

**Comment by cjw85** [comment]
@e-sollier,

It may be worth pointing out that parsing of the MM and ML SAM tags is supported in htslib and is working its way into pysam [pysam!1052](https://github.com/pysam-developers/pysam/issues/1052). We have also a project for creating a BED file with per-reference position counts: [modbam2bed](https://github.com/epi2me-labs/modbam2bed). As well as the core program, the project contains a minimal Python library for interacting with modified base data from BAM files.
