### ISSUE TITLE
Sample data to test new models

### ISSUE THREAD

**Issue by SanityTree** [nanoporetech/remora#91]
Hello, 

This is less of an issue and more of a question. Is it possible to get example data to test the new 5mC models? We methylate DNA using methyltransferases in vitro, and have only used the R9.4.1's with Tombo to give us methylation sites, and I have never had to use Remora before. With the R9.4.1's becoming obsolete this year we will have to move onto R10.4.1's, so I am happy to see models have been developed for picking out 5mC's. I just wanted to know if there was a way for me to test the models before I start working with it?

**Comment by marcus1487** [comment]
There is a small amount of [test data included with the repository here](https://github.com/nanoporetech/remora/tree/master/tests/data). I would suggest this data for small test purposes to get a sense of the model output and pipelines.

**Comment by SanityTree** [comment]
That’s great, thank you.
