### ISSUE TITLE
Is the MM tag correctly encoded for reverse-strand reads?

### ISSUE THREAD

**Issue by Shians** [nanoporetech/remora#93]
I am trying to write code to translate read-anchored positions to reference-anchored positions and this is troubling me.

I used Guppy 6.3.4 to call 5mC methylation, and the resulting bam contains an entry like so 

```
66ee6735-055d-4051-8dcf-1c20337a91bd	16	chr1	3965	0	12S13M2I2M1I13M2D256M1D23M1I15M76S	*	0	414	GGGCTGACTGTGGGGCAGATGGGGATGGTGAGGCAGGGCCCTCGGTCCCGGTGTGACGGCCTCCTGCGCCACTAAAGTCAGAGCGCGTTATTAAGCCCCATCAGTTCTGTAAATTCAAACTGAAACGGAGCTATTACTGGGGAGGGCTGATGTCCCAGTTCTTGTTTAACTTGGAAGAAAGATTTTCACCAAGAGGCAGTACAAAGATGGCAGATAACTTCATTGAAAAGAAACACAGTGTAAAGAGCTTATTGTAGAAAAATAGGGAGGAGTGGGCTGAGCGTGCATTAAAACAGCCTAGAGTCCTGTTCAGGAAATTTTATTTTGGGACTTCTTCAGGTGCTGGAAAACTTGTGTCCCAGTTACCAGGTTAACCTTAGCAATACGTAACTGAACGAAGTAGAATACATATAG	#$$%%'))*,-036;8888,:)((((()),CA?<<<.),''()*--**+0;=A?BBBBDFFF@>>=>AHI{OIQMKHDBB?@?C@??>>CCBFC>7777DB???B<<64/644540///0;6644479<=>AIFBBA579?DEECBAEHQMJHHKGBAAA?BCKPGJJJKGMMFGEDGHFK{JMMGHHFGIFFJDDDB<:;;;?@@@>CKMKKIFFFGHIICBB;@JOAK{{PKHHJHIKLKFGCFEGKJPIJOMLP{{NFDA0?4???A<EDFCGEIFFFGHG@CDCAEGGGCE;65588>>?@?LHDDGHKO{PTNJLG395;(3<3OKPKKJMHHFFFD1,,+*((*./:EEFFDCCBFCCB@EIJEFEDEDEGHEDECCBBABCJKBB::81//)&$##$%&,))&&&%$	AS:i:598	MD:Z:13C14^TT13G242^A38	NM:i:9	cm:i:41	de:f:0.0214	ms:i:600	nn:i:0	s1:i:245	s2:i:255	tp:A:P	MM:Z:C+m?,3,1,21,44,4,0,3,2,3,1;	ML:B:C,2,2,255,1,255,255,2,1,1,255	qs:i:15	mx:i:2	ch:i:20	rn:i:370129	st:Z:2023-03-26T22:05:59Z	f5:Z:PAM86664_pass_barcode03_470065a5_00bf7401_2238.fast5	ns:i:7156	ts:i:0	RG:Z:00bf7401bb5b90a05936b935b90ac2c0c7a54c65_dna_r10.4.1_e8.2_sup@v3.5.1_barcode03-730F9784
```

The 16 (0x10) tag indicates that SEQ is reverse-complemented, indicating that the read mapped to the reverse strand. The issue is that I think the MM tag now corresponds to the original read rather than the reverse-complement shown in SEQ. It's obvious from the sequence that the MM tag does not correspond to CG sites. I've inserted "_" before each C for readability, but it's clear that the 4th and 6th C are not CG dinucleotides.

```
GGG_CTGA_CTGTGGGG_CAGATGGGGATGGTGAGG_CAGGG_C_C_CT_CGGT_C_C_CGGTGTGA_CGG_C_CT_C_CTG_CG_C_CA_CTAAAGT_CAGAG_CG_CGTTATTAAG_C_C_C_CAT_CAGTT_CTGTAAATT_CAAA_CTGAAA_CGGAG_CTATTA_CTGGGGAGGG_CTGATGT_C_C_CAGTT_CTTGTTTAA_CTTGGAAGAAAGATTTT_CA_C_CAAGAGG_CAGTA_CAAAGATGG_CAGATAA_CTT_CATTGAAAAGAAA_CA_CAGTGTAAAGAG_CTTATTGTAGAAAAATAGGGAGGAGTGGG_CTGAG_CGTG_CATTAAAA_CAG_C_CTAGAGT_C_CTGTT_CAGGAAATTTTATTTTGGGA_CTT_CTT_CAGGTG_CTGGAAAA_CTTGTGT_C_C_CAGTTA_C_CAGGTTAA_C_CTTAG_CAATA_CGTAA_CTGAA_CGAAGTAGAATA_CATATAG
```

While in the reverse-complement of SEQ we can see that the offsets correctly refer to CG dinucleotides.

```
_CTATATGTATT_CTA_CTT_CGTT_CAGTTA_CGTATTG_CTAAGGTTAA_C_CTGGTAA_CTGGGA_CA_CAAGTTTT_C_CAG_CA_C_CTGAAGAAGT_C_C_CAAAATAAAATTT_C_CTGAA_CAGGA_CT_CTAGG_CTGTTTTAATG_CA_CG_CT_CAG_C_C_CA_CT_C_CT_C_C_CTATTTTT_CTA_CAATAAG_CT_CTTTA_CA_CTGTGTTT_CTTTT_CAATGAAGTTAT_CTG_C_CAT_CTTTGTA_CTG_C_CT_CTTGGTGAAAAT_CTTT_CTT_C_CAAGTTAAA_CAAGAA_CTGGGA_CAT_CAG_C_C_CT_C_C_C_CAGTAATAG_CT_C_CGTTT_CAGTTTGAATTTA_CAGAA_CTGATGGGG_CTTAATAA_CG_CG_CT_CTGA_CTTTAGTGG_CG_CAGGAGG_C_CGT_CA_CA_C_CGGGA_C_CGAGGG_C_C_CTG_C_CT_CA_C_CAT_C_C_C_CAT_CTG_C_C_C_CA_CAGT_CAG_C_C_C
```

I struggle to fully understand the SAM spec but it sounds to me like this should have been encoded as "MM:Z:G-m?" with offsets corresponding to counting from the 5' end of SEQ. Please let me know if this had been considered and whether there's anything from the SAM spec authors that clarifies the correct interpretation.

**Comment by Shians** [comment]
Upon re-reading the optional fields spec I see that this is permitted.

> This permits modifications to be listed on either strand with the rare potential for both strands to have a modification at the same site. If SAM FLAG 0x10 is set, indicating that SEQ has been reverse complemented from the sequence observed by the sequencing machine, note that these base modification field values will be in the opposite orientation to SEQ and other derived SAM fields.

**Comment by ArtRand** [comment]
@Shians you may try using `modkit extract` ([docs](https://nanoporetech.github.io/modkit/intro_extract.html), [repo](https://github.com/nanoporetech/modkit/)) if you want to pull out read-level information.
