### ISSUE TITLE
All context mod bases from dorado for duplex reads

### ISSUE THREAD

**Issue by gwl2** [nanoporetech/remora#94]
We have had great success with the all context mod bases model for our simplex reads and now want to test it for the duplex reads.
Simplex is pretty easy with dorado:
```shell
dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.2.0 ./ --modified-bases 5mC 6mA > calls.bam
```
However there is no option for duplex reads yet. In the dorados github issues it was suggest to use remora to do that (remora infer duplex_from_pod5_and_bam).
If I have the duplex.bam file from dorado. What would be the correct remora command and where do I get the right model from?

```shell
remora infer duplex_from_pod5_and_bam data.pod5 duplex.bam --model ??? --out-bam duplex.mod_bases.bam --log-filename duplex.mod_bases.log
``` 
I can't find the right model in remora and  dorado also has not single all context model:
dna_r10.4.1_e8.2_400bps_sup@v4.2.0
dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2
dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2
dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v2

Do I have to supply remora with all these models?

Help would be highly appreciated. Thanks.

**Comment by ArtRand** [comment]
Hello @gwl2

For duplex mod-calling you should use the remora model associated with the simplex basecaller. In this case, you used SUP so any of the modified base models you've mentioned would work. The first model (`dna_r10.4.1_e8.2_400bps_sup@v4.2.0`) is not a modified base model. You'll need to run `remora model download` to get all of the available models. Lastly, as per the documentation `duplex_from_pod5_and_bam` requires the `simplex_bam`, the `duplex_bam` and the `duplex_read_pairs`.

**Comment by marcus1487** [comment]
Dorado does not currently support modified base calls on duplex basecalls. Remora can be used for this, but is not well documented at the moment. In the long term we are aiming to produce better support for modified base calls on duplex reads.

You can see the full help for the Remora command with the `remora infer duplex_from_pod5_and_bam -h` command. This requires the original POD5 file, the simplex bam file (for the simplex move table), the duplex bam file (for the duplex canonical sequence) and a duplex read pairs file (text file with two columns containing the simplex read id pairs). Again we are aiming to make this pipeline much easier to run in the near future, but hopefully this command can get you going for now. 

For the models you are looking for the following models (which are just the pytorch format version of the models shipped with dorado): `dna_r10.4.1_e8.2_5khz_400bps_sup_v4.2.0_5mc_v2.pt`, `dna_r10.4.1_e8.2_5khz_400bps_sup_v4.2.0_6ma_v2.pt`
