### ISSUE TITLE
Training Dataset

### ISSUE THREAD

**Issue by aCoalBall** [nanoporetech/remora#99]
Hi there,

I would like to know on what dataset remora was trained?

**Comment by HaoDreamlong** [comment]
Hi @marcus1487 ,
The link you posted  now returns 404 – File not found.
Could you please check whether the resource has moved or been renamed and update the link?
Thanks a lot!

**Comment by marcus1487** [comment]
It looks like the resource was move [here](https://nanoporetech.com/resource-centre/ncm22-nanopore-modified-base-update).
